{
  "hash": "478fa08546d86f0d13b26c6d132a0e6d",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: DATASCI 350 - Data Science Computing\nsubtitle: Lecture 22 - SQL Revision with DuckDB\nauthor:\n  - name: Danilo Freire\n    email: danilo.freire@emory.edu\n    affiliations: \"Department of Data and Decision Sciences <br> Emory University\"\nformat:\n  clean-revealjs:\n    self-contained: false\n    code-overflow: wrap\n    footer: \"[SQL with DuckDB](https://danilofreire.github.io/datasci350/lectures/lecture-22/22-sql-revision.html)\"\ntransition: slide\ntransition-speed: default\nscrollable: true\nengine: python3\nexecute:\n  freeze: auto\n  cache: true\nrevealjs-plugins:\n  - fontawesome\n  - multimodal\neditor:\n  render-on-save: true\n---\n\n# Hello again! 😊 <br> I hope you had a good week {background-color=\"#1B3A6B\"}\n\n# Brief recap 📚 {background-color=\"#1B3A6B\"}\n\n## Parallel computing fundamentals\n### Where lecture 21 left us\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- Last class we covered [parallel and scalable computing]{.alert}:\n  - [`map`]{.alert}, embarrassingly parallel problems, `joblib` and `concurrent.futures`\n  - [Big O]{.alert}: parallelism cuts the constant, the complexity class stays the same\n  - [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law): the serial share caps your speed-up, so measure before scaling\n  - [The GIL](https://en.wikipedia.org/wiki/Global_interpreter_lock): threads for I/O, processes for CPU, C/Rust libraries sidestep it\n  - [Dask]{.alert}: lazy arrays and DataFrames for bigger-than-RAM data\n:::\n\n:::{.column width=\"50%\"}\n- We ended with a promise: some engines [parallelise for you]{.alert}, with no cluster to manage\n- DuckDB is one of them, and today we use it to revise [SQL]{.alert}\n- In Lecture 02 you voted for a SQL revision over a Polars class\n- All queries today run on the [WDI panel]{.alert} you built in Module 06\n\n:::{style=\"text-align: center; margin-top: -10px;\"}\n[![](figures/parallel.png){width=\"52%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/parallel.png\"}\n:::\n:::\n:::\n:::\n\n# Today's agenda {background-color=\"#1B3A6B\"}\n\n## Lecture overview\n### What we will cover today\n\n:::{style=\"margin-top: 12px; font-size: 21px;\"}\n:::{.columns}\n::::{.column width=\"50%\"}\n[1. Why SQL and why DuckDB]{.alert}\n\n- A declarative language every engine speaks\n- `import duckdb` is the whole setup\n\n[2. First queries]{.alert}\n\n- `SELECT`, `WHERE`, `ORDER BY`, `LIMIT`\n- `IN`, `BETWEEN`, `LIKE`, and the order a query really runs in\n\n[3. Aggregating]{.alert}\n\n- `COUNT`, `AVG`, `GROUP BY`, `HAVING`\n- What `COUNT` does when values are missing\n::::\n\n::::{.column width=\"50%\"}\n[4. NULLs, CASE and windows]{.alert}\n\n- `IS NULL`, `COALESCE`, income bands with `CASE`\n- A window function beside a `GROUP BY`\n\n[5. Joins]{.alert}\n\n- Primary keys, foreign keys, and the `ON` clause\n- `INNER`, `LEFT`, `FULL OUTER` on two tiny tables\n\n[6. SQL in Python]{.alert}\n\n- Querying a pandas DataFrame by its variable name\n- The same queries in plain `sqlite3`, which assignment 09 uses\n- DuckDB on 200 million rows\n::::\n:::\n:::\n\n# Why SQL, why DuckDB 🦆 {background-color=\"#1B3A6B\"}\n\n## Why SQL\n### You describe the answer, the engine finds it\n\n:::{style=\"margin-top: 15px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- [SQL]{.alert} is a language for asking questions of tables\n- It is [declarative]{.alert}: you say what you want, and the engine decides how to compute it\n  - No loops, no index lookups, no merge strategy\n  - The engine can reorder the query, read fewer columns, or use every core\n- SQL is about fifty years old, and data job adverts list it more often than any Python library\n- Dialects differ in the details, but `SELECT`, `WHERE`, `GROUP BY` and `JOIN` are the same in DuckDB, SQLite, PostgreSQL, BigQuery and Snowflake\n:::\n\n:::{.column width=\"48%\"}\n:::{style=\"text-align: center; margin-top: -10px;\"}\n[![](figures/duckdb-docs-sql-2026.png){width=\"100%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/duckdb-docs-sql-2026.png\"}\n\n:::{style=\"font-size: 17px;\"}\nDuckDB's SQL introduction: <https://duckdb.org/docs/stable/sql/introduction>\n:::\n:::\n:::\n:::\n:::\n\n## Why DuckDB for a revision class\n### An in-process engine with no setup\n\n:::{style=\"margin-top: 15px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- [Zero setup]{.alert}: `pip install duckdb`, then `import duckdb`. No server, no password\n- [In-process]{.alert}: the database runs inside your Python session, like SQLite (\"SQLite for analytics\")\n- [Reads files by name]{.alert}: a Parquet or CSV path goes straight in the `FROM` clause\n- Reads a pandas DataFrame by its variable name too (more on this later)\n- [Columnar]{.alert} and [parallel]{.alert} underneath, so the same `GROUP BY` works on 200 million rows\n- Version on my laptop: [DuckDB 1.5.5]{.alert}\n:::\n\n:::{.column width=\"48%\"}\n:::{style=\"text-align: center; margin-top: -10px;\"}\n[![](figures/duckdb-home-2026.png){width=\"100%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/duckdb-home-2026.png\"}\n\n:::{style=\"font-size: 17px;\"}\nSource: <https://duckdb.org>\n:::\n:::\n\n:::{style=\"background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 10px;\"}\nAssignment 09 uses `sqlite3` from the standard library. The sqlite3 section runs the same queries there, so nothing today is DuckDB-only\n:::\n:::\n:::\n:::\n\n# First queries {background-color=\"#1B3A6B\"}\n\n## Querying a Parquet file\n### The file path goes in the FROM clause\n\n:::{style=\"margin-top: 15px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- The WDI panel: 59,024 rows of country, indicator, year and value\n- `duckdb.sql()` takes a query string and returns a result you can print\n- The path goes in [single quotes]{.alert}: single quotes mean text, double quotes mean a column name\n- No `read_parquet`, no connection, no cursor\n- The [column types]{.alert} under the names come from the Parquet file\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#fd989adb .cell cache='true' execution_count=2}\n``` {.python .cell-code}\nimport duckdb\n\nduckdb.sql(\"\"\"\n    SELECT *\n    FROM '../lecture-19/data/wdi_panel.parquet'\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n┌─────────┬─────────┬────────────────┬───────┬──────────────────┐\n│ country │  iso3   │   indicator    │ year  │      value       │\n│ varchar │ varchar │    varchar     │ int16 │      double      │\n├─────────┼─────────┼────────────────┼───────┼──────────────────┤\n│ Aruba   │ ABW     │ co2_per_capita │  1990 │ 3.20303411789078 │\n│ Aruba   │ ABW     │ co2_per_capita │  1991 │ 3.43571688721622 │\n│ Aruba   │ ABW     │ co2_per_capita │  1992 │  3.6345192377364 │\n│ Aruba   │ ABW     │ co2_per_capita │  1993 │ 3.41453484426953 │\n│ Aruba   │ ABW     │ co2_per_capita │  1994 │ 3.68322701204975 │\n└─────────┴─────────┴────────────────┴───────┴──────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Creating a view\n### One name for the file\n\n:::{style=\"margin-top: 15px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"42%\"}\n- A [view]{.alert} is a saved query that behaves like a table\n  - Ours is called `wdi`, so every later query says `FROM wdi` instead of the file path\n  - It holds no data: DuckDB re-reads the Parquet file each time\n  - `OR REPLACE` makes the cell safe to re-run\n- [`DESCRIBE`]{.alert} lists the columns and their types\n- [`SUMMARIZE`]{.alert} shows min, max, count and the share of missing values per column\n- 11.06% of `value` is missing (more on this in the NULLs section)\n:::\n\n:::{.column width=\"58%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#da930ebb .cell cache='true' execution_count=3}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    CREATE OR REPLACE VIEW wdi AS\n    SELECT * FROM '../lecture-19/data/wdi_panel.parquet'\n\"\"\")\n\nduckdb.sql(\"\"\"\n    SELECT COUNT(*) AS n_rows,\n           COUNT(DISTINCT country) AS countries,\n           COUNT(DISTINCT indicator) AS indicators\n    FROM wdi\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n┌────────┬───────────┬────────────┐\n│ n_rows │ countries │ indicators │\n│ int64  │   int64   │   int64    │\n├────────┼───────────┼────────────┤\n│  59024 │       217 │          8 │\n└────────┴───────────┴────────────┘\n```\n:::\n:::\n\n\n::: {#208fdf8c .cell cache='true' execution_count=4}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT column_name, min, max, null_percentage\n    FROM (SUMMARIZE SELECT country, year, value FROM wdi)\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n┌─────────────┬─────────────┬──────────────┬─────────────────┐\n│ column_name │     min     │     max      │ null_percentage │\n│   varchar   │   varchar   │   varchar    │  decimal(9,2)   │\n├─────────────┼─────────────┼──────────────┼─────────────────┤\n│ country     │ Afghanistan │ Zimbabwe     │            0.00 │\n│ year        │ 1990        │ 2023         │            0.00 │\n│ value       │ 0.0         │ 1438069596.0 │           11.06 │\n└─────────────┴─────────────┴──────────────┴─────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## SELECT, aliases, ORDER BY, LIMIT\n### Picking columns and sorting the result\n\n:::{style=\"margin-top: 15px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- `SELECT` lists the columns you want (`*` means all of them)\n- [`AS`]{.alert} renames a column in the output. The new name is an [alias]{.alert}\n- `SELECT` can also compute, e.g. `ROUND(value, 0)`\n- `ORDER BY value DESC` sorts high to low (`ASC` is the default)\n- [`LIMIT`]{.alert} caps the rows returned. Use it while exploring\n- Monaco, at 161,263 dollars per person, is the panel's maximum\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#0a508898 .cell cache='true' execution_count=5}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, year,\n           ROUND(value, 0) AS gdp_pc\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND year = 2020\n    ORDER BY value DESC\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\n┌─────────────┬───────┬──────────┐\n│   country   │ year  │  gdp_pc  │\n│   varchar   │ int16 │  double  │\n├─────────────┼───────┼──────────┤\n│ Monaco      │  2020 │ 161263.0 │\n│ Luxembourg  │  2020 │ 105274.0 │\n│ Bermuda     │  2020 │  98846.0 │\n│ Isle of Man │  2020 │  86595.0 │\n│ Switzerland │  2020 │  86294.0 │\n└─────────────┴───────┴──────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## WHERE with AND, OR and NOT\n### Filtering rows with WHERE\n\n:::{style=\"margin-top: 15px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- [`WHERE`]{.alert} keeps rows whose condition is true\n- `AND` requires both sides, `OR` requires either, `NOT` flips a condition\n- The brackets around the `OR` matter: `AND` binds tighter\n- Text goes in single quotes, and comparisons are case-sensitive in DuckDB\n- Without the `NOT`, Japan would fill the list\n- All five rows are from 2020, although we asked for 2000 too: life expectancy rose almost everywhere\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#4414c8fd .cell cache='true' execution_count=6}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, year,\n           ROUND(value, 1) AS life_exp\n    FROM wdi\n    WHERE indicator = 'life_expectancy'\n      AND (year = 2000 OR year = 2020)\n      AND NOT country = 'Japan'\n    ORDER BY value DESC\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n┌──────────────────────┬───────┬──────────┐\n│       country        │ year  │ life_exp │\n│       varchar        │ int16 │  double  │\n├──────────────────────┼───────┼──────────┤\n│ Monaco               │  2020 │     86.1 │\n│ Hong Kong SAR, China │  2020 │     85.5 │\n│ Macao SAR, China     │  2020 │     84.1 │\n│ Singapore            │  2020 │     83.5 │\n│ Korea, Rep.          │  2020 │     83.4 │\n└──────────────────────┴───────┴──────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## IN, BETWEEN, LIKE and ILIKE\n### Shorthand for the conditions you write most often\n\n:::{style=\"margin-top: 15px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- [`IN`]{.alert} replaces a chain of `OR` comparisons\n- [`BETWEEN`]{.alert} includes both ends: 2018, 2019 and 2020\n\n:::{style=\"font-size: 20px;\"}\n\n::: {#8bd44245 .cell cache='true' execution_count=7}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, year,\n           ROUND(value, 1) AS life_exp\n    FROM wdi\n    WHERE indicator = 'life_expectancy'\n      AND country IN ('Brazil', 'Japan', 'Germany')\n      AND year BETWEEN 2018 AND 2020\n    ORDER BY country, year\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\n┌─────────┬───────┬──────────┐\n│ country │ year  │ life_exp │\n│ varchar │ int16 │  double  │\n├─────────┼───────┼──────────┤\n│ Brazil  │  2018 │     75.6 │\n│ Brazil  │  2019 │     75.8 │\n│ Brazil  │  2020 │     74.5 │\n│ Germany │  2018 │     80.9 │\n│ Germany │  2019 │     81.3 │\n└─────────┴───────┴──────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"48%\"}\n- [`LIKE`]{.alert} matches a text pattern. `%` stands for any run of characters, `_` for exactly one\n- [`ILIKE`]{.alert} is the same test ignoring case (DuckDB only)\n\n:::{style=\"font-size: 20px;\"}\n\n::: {#654fed36 .cell cache='true' execution_count=8}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT DISTINCT country\n    FROM wdi\n    WHERE country LIKE 'United%'\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n┌──────────────────────┐\n│       country        │\n│       varchar        │\n├──────────────────────┤\n│ United States        │\n│ United Arab Emirates │\n│ United Kingdom       │\n└──────────────────────┘\n```\n:::\n:::\n\n\n:::\n\n:::{style=\"background: rgba(230, 57, 70, 0.1); padding: 12px; border-radius: 10px; font-size: 18px; margin-top: 10px;\"}\nWrite `'united%'` in lower case with plain `LIKE` and DuckDB returns [zero rows]{.alert}. SQLite would return all three. The sqlite3 section has the full list of these differences\n:::\n:::\n:::\n:::\n\n## The order a query really runs in\n### How the engine evaluates a query\n\n:::{style=\"margin-top: 10px; font-size: 20px;\"}\n:::{style=\"text-align: center;\"}\n[![](figures/sql-evaluation-order.png){width=\"66%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/sql-evaluation-order.png\"}\n:::\n\n:::{.columns}\n:::{.column width=\"50%\"}\n- You write `SELECT` first, but the engine runs it fifth\n- `FROM` finds the rows, `WHERE` filters them, `GROUP BY` forms the groups, `HAVING` filters groups, then `SELECT` computes the output\n:::\n\n:::{.column width=\"50%\"}\n- An aggregate cannot go in `WHERE`: the groups do not exist yet\n- Standard SQL (and PostgreSQL) rejects a `SELECT` alias inside `WHERE`. DuckDB and SQLite accept it\n:::\n:::\n:::\n\n# Aggregating {background-color=\"#1B3A6B\"}\n\n## GROUP BY\n### One row of output per group\n\n:::{style=\"margin-top: 15px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- An [aggregate function]{.alert} reads many rows and returns one number\n  - Without `GROUP BY`, the whole filtered table is one group\n- [`GROUP BY`]{.alert} splits the rows into groups and applies the aggregate to each one\n- Every column in `SELECT` must be in the `GROUP BY` or inside an aggregate\n- Eight indicators, eight rows\n- `primary_enrolment_net` has 217 rows in 2020 and no values, so `COUNT(value)` is 0 and `AVG` is NULL\n- Mean population is 36 million, mean fertility 2.49: averaging across indicators would be meaningless\n- Grouping by two columns gives one row per pair: [[Appendix 05]{.button}](#sec-appendix-05)\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#662d89f2 .cell cache='true' execution_count=9}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT indicator,\n           COUNT(value) AS n,\n           ROUND(AVG(value), 2) AS mean_value\n    FROM wdi\n    WHERE year = 2020\n    GROUP BY indicator\n    ORDER BY indicator\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n┌───────────────────────┬───────┬─────────────┐\n│       indicator       │   n   │ mean_value  │\n│        varchar        │ int64 │   double    │\n├───────────────────────┼───────┼─────────────┤\n│ co2_per_capita        │   203 │        4.45 │\n│ fertility_rate        │   217 │        2.49 │\n│ gdp_per_capita        │   208 │    16149.94 │\n│ internet_users_pct    │   184 │       64.11 │\n│ life_expectancy       │   217 │        72.5 │\n│ population            │   217 │ 36084236.48 │\n│ primary_enrolment_net │     0 │        NULL │\n│ urban_pop_pct         │   217 │       61.82 │\n└───────────────────────┴───────┴─────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## WHERE and HAVING\n### Filtering before and after grouping\n\n:::{style=\"margin-top: 15px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- `WHERE` filters rows before grouping. [`HAVING`]{.alert} filters groups after, so only `HAVING` can take an aggregate\n- `WHERE year >= 2010` drops the old rows, `HAVING AVG(value) > 60000` drops the poorer countries\n- \"Which years count?\" is a row question. \"Which countries qualify?\" is a group question\n- Small economies with financial centres dominate: Monaco, Liechtenstein and Bermuda all have under 100,000 people\n- `ORDER BY` can use an alias (`mean_gdp` here)\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#c74ade80 .cell cache='true' execution_count=10}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country,\n           ROUND(AVG(value), 0) AS mean_gdp\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND year >= 2010\n    GROUP BY country\n    HAVING AVG(value) > 60000\n    ORDER BY mean_gdp DESC\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\n┌───────────────┬──────────┐\n│    country    │ mean_gdp │\n│    varchar    │  double  │\n├───────────────┼──────────┤\n│ Monaco        │ 173083.0 │\n│ Liechtenstein │ 167187.0 │\n│ Bermuda       │ 107724.0 │\n│ Luxembourg    │ 106545.0 │\n│ Switzerland   │  86948.0 │\n└───────────────┴──────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## COUNT(\\*) and COUNT(value)\n### Counting rows and counting values\n\n:::{style=\"margin-top: 15px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- `COUNT`, `SUM`, `AVG`, `MIN` and `MAX` cover almost everything you will write\n- [`COUNT(*)`]{.alert} counts rows. [`COUNT(value)`]{.alert} counts rows where `value` is present\n- `AVG`, `SUM`, `MIN` and `MAX` skip missing values silently\n- The difference between the two counts is the number of holes in the column\n- Internet use has 217 country rows in each year, but 9 values are missing in 1990, 21 in 2000 and 33 in 2020\n- Coverage gets [worse]{.alert} over time: small territories join the panel and never report the series\n- Run this on any column before you trust its mean (`SUMMARIZE` does it for the whole file)\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#5423eb0b .cell cache='true' execution_count=11}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT year,\n           COUNT(*) AS n_rows,\n           COUNT(value) AS with_value,\n           COUNT(*) - COUNT(value) AS missing\n    FROM wdi\n    WHERE indicator = 'internet_users_pct'\n      AND year IN (1990, 2000, 2020)\n    GROUP BY year\n    ORDER BY year\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\n┌───────┬────────┬────────────┬─────────┐\n│ year  │ n_rows │ with_value │ missing │\n│ int16 │ int64  │   int64    │  int64  │\n├───────┼────────┼────────────┼─────────┤\n│  1990 │    217 │        208 │       9 │\n│  2000 │    217 │        196 │      21 │\n│  2020 │    217 │        184 │      33 │\n└───────┴────────┴────────────┴─────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Try it yourself! 🧠 {#sec-exercise-01}\n### Five minutes\n\n:::{style=\"margin-top: 20px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\nWhich countries have had the highest life expectancy since 2010?\n\n1. Open a Python file or a notebook\n2. Import `duckdb`\n3. Create the `wdi` view over `../lecture-19/data/wdi_panel.parquet`\n4. Keep only the rows for `life_expectancy`\n5. Keep only the years from 2010 onwards\n6. Compute the mean of `value` for each country\n7. Keep the countries whose mean is above 82\n8. Sort from highest to lowest\n9. Return the top five, rounded to one decimal\n:::\n\n:::{.column width=\"48%\"}\nWhat to look for:\n\n- The filter on `year` and the filter on the average go in [different clauses]{.alert}. One of them is `WHERE`\n- `ORDER BY` can name the alias you created in `SELECT`\n- Five rows, all above 83 years. Four are small states or city economies\n- Japan is the only large country there, in fourth place\n- An error about an aggregate in `WHERE`? Re-read the evaluation-order ladder\n\n:::{style=\"background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;\"}\nSolution and the full output: [[Appendix 01]{.button}](#sec-appendix-01)\n:::\n:::\n:::\n:::\n\n# NULLs, CASE and windows {background-color=\"#1B3A6B\"}\n\n## Missing values\n### Working with NULL\n\n:::{style=\"margin-top: 15px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- A NULL means \"unknown\", so it is neither zero nor an empty string\n- Test it with [`IS NULL`]{.alert}, never with `=`\n- [`COALESCE(a, b)`]{.alert} returns `a`, or `b` when `a` is NULL\n- We ask for five countries and get four rows: Somalia has no CO2 row at all for 2022\n- `COALESCE` cannot fix a missing [row]{.alert}, only a missing value. A `LEFT JOIN` can (see the joins section)\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#45c538ba .cell cache='true' execution_count=12}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country,\n           ROUND(COALESCE(value, 0), 1) AS co2_filled\n    FROM wdi\n    WHERE indicator = 'co2_per_capita'\n      AND year = 2022\n      AND country IN ('Brazil', 'Japan', 'Somalia',\n                      'Germany', 'Eritrea')\n    ORDER BY country\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\n┌─────────┬────────────┐\n│ country │ co2_filled │\n│ varchar │   double   │\n├─────────┼────────────┤\n│ Brazil  │        2.3 │\n│ Eritrea │        0.2 │\n│ Germany │        7.9 │\n│ Japan   │        8.4 │\n└─────────┴────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## CASE\n### Writing an if-else ladder inside a SELECT\n\n:::{style=\"margin-top: 12px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#62e0adc9 .cell cache='true' execution_count=13}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, ROUND(value, 0) AS gdp_pc,\n        CASE\n            WHEN value IS NULL  THEN 'No data'\n            WHEN value >= 13846 THEN 'High income'\n            WHEN value >= 4466  THEN 'Upper middle'\n            WHEN value >= 1136  THEN 'Lower middle'\n            ELSE 'Low income'\n        END AS income_band\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita' AND year = 2020\n      AND country IN ('Norway', 'China', 'India',\n                      'Burundi', 'Brazil')\n    ORDER BY value DESC NULLS LAST\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```\n┌─────────┬─────────┬──────────────┐\n│ country │ gdp_pc  │ income_band  │\n│ varchar │ double  │   varchar    │\n├─────────┼─────────┼──────────────┤\n│ Norway  │ 78387.0 │ High income  │\n│ China   │ 10573.0 │ Upper middle │\n│ Brazil  │  8435.0 │ Upper middle │\n│ India   │  1807.0 │ Lower middle │\n│ Burundi │   263.0 │ Low income   │\n└─────────┴─────────┴──────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"45%\"}\n- [`CASE`]{.alert} tests conditions in order and stops at the first true one, like `if`/`elif`\n- The thresholds are the World Bank's income bands: 13,846, 4,466 and 1,136 dollars per person\n- The `IS NULL` test comes [first]{.alert} on purpose: at the bottom, a missing value would fall through to `ELSE` and become \"Low income\"\n- `ELSE` catches everything else. Without it, unmatched rows get NULL\n- `NULLS LAST` sends unknown values to the bottom of the sort\n- The result is a new column you can group by, join on, or export\n:::\n:::\n:::\n\n## Window functions\n### Adding a group-level number to every row\n\n:::{style=\"margin-top: 15px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#551a6205 .cell cache='true' execution_count=14}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, ROUND(value, 0) AS gdp_pc,\n           ROUND(AVG(value) OVER (PARTITION BY year), 0)\n               AS world_mean,\n           RANK() OVER (ORDER BY value DESC) AS world_rank\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND year = 2020 AND value IS NOT NULL\n    ORDER BY world_rank\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```\n┌─────────────┬──────────┬────────────┬────────────┐\n│   country   │  gdp_pc  │ world_mean │ world_rank │\n│   varchar   │  double  │   double   │   int64    │\n├─────────────┼──────────┼────────────┼────────────┤\n│ Monaco      │ 161263.0 │    16150.0 │          1 │\n│ Luxembourg  │ 105274.0 │    16150.0 │          2 │\n│ Bermuda     │  98846.0 │    16150.0 │          3 │\n│ Isle of Man │  86595.0 │    16150.0 │          4 │\n│ Switzerland │  86294.0 │    16150.0 │          5 │\n└─────────────┴──────────┴────────────┴────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"45%\"}\n- `GROUP BY` collapses each group to one row. A [window function]{.alert} keeps every row and adds a value computed across the group\n- [`OVER`]{.alert} turns a function into a window function. `PARTITION BY year` defines the group\n- `world_mean` is 16,150 on every row, the same as a plain `AVG` over 2020\n- [`RANK()`]{.alert} needs an `ORDER BY` inside the `OVER`\n- All 208 countries survive this query; we print five\n:::\n:::\n:::\n\n# Joins {background-color=\"#1B3A6B\"}\n\n## Two small tables\n### Keys, and the two tables we will join\n\n<style>#two-small-tables .cell-output pre code { font-size: 0.8em !important; }</style>\n\n:::{style=\"margin-top: 6px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"58%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#375145e1 .cell cache='true' execution_count=15}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    CREATE OR REPLACE TABLE gdp2020 AS\n    SELECT country, iso3, ROUND(value, 0) AS gdp_per_capita\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita' AND year = 2020\n      AND iso3 IN ('USA','BRA','CHN','IND','DEU','JPN')\n\"\"\")\n\nduckdb.sql(\"\"\"\n    CREATE OR REPLACE TABLE regions\n        (iso3 VARCHAR PRIMARY KEY, region VARCHAR)\n\"\"\")\n\nduckdb.sql(\"\"\"\n    INSERT INTO regions VALUES\n        ('USA', 'North America'), ('BRA', 'Latin America'),\n        ('CHN', 'East Asia'),     ('IND', 'South Asia'),\n        ('DEU', 'Europe'),        ('KOR', 'East Asia')\n\"\"\")\n\nduckdb.sql(\"SELECT * FROM regions ORDER BY iso3\")\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\n┌─────────┬───────────────┐\n│  iso3   │    region     │\n│ varchar │    varchar    │\n├─────────┼───────────────┤\n│ BRA     │ Latin America │\n│ CHN     │ East Asia     │\n│ DEU     │ Europe        │\n│ IND     │ South Asia    │\n│ KOR     │ East Asia     │\n│ USA     │ North America │\n└─────────┴───────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"42%\"}\n:::{style=\"font-size: 19px;\"}\n- A [table]{.alert} is a grid with named columns, one type per column\n- `CREATE TABLE` creates it, `INSERT INTO ... VALUES` adds rows\n- A [primary key]{.alert} identifies a row uniquely (no duplicates, no NULLs): `iso3` in `regions`\n- A [foreign key]{.alert} points at another table's primary key: `iso3` in `gdp2020`. A join follows it with `ON g.iso3 = r.iso3`\n- Six rows on each side, with two mismatches: [`JPN`]{.alert} has a GDP figure and no region, [`KOR`]{.alert} a region and no GDP figure\n- East Asia holds two codes (this matters for the second exercise)\n:::\n:::\n:::\n:::\n\n## INNER JOIN\n### Only the rows that match on both sides\n\n:::{style=\"margin-top: 15px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#48454c5f .cell cache='true' execution_count=16}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT g.country, r.region, g.gdp_per_capita\n    FROM gdp2020 AS g\n    INNER JOIN regions AS r ON g.iso3 = r.iso3\n    ORDER BY g.country\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\n┌───────────────┬───────────────┬────────────────┐\n│    country    │    region     │ gdp_per_capita │\n│    varchar    │    varchar    │     double     │\n├───────────────┼───────────────┼────────────────┤\n│ Brazil        │ Latin America │         8435.0 │\n│ China         │ East Asia     │        10573.0 │\n│ Germany       │ Europe        │        42373.0 │\n│ India         │ South Asia    │         1807.0 │\n│ United States │ North America │        59534.0 │\n└───────────────┴───────────────┴────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"48%\"}\n- [`ON`]{.alert} says which columns must agree: the `iso3` code on each side\n- `AS g` and `AS r` are table aliases, so `g.iso3` and `r.iso3` stay apart\n- Six rows on the left, six on the right, [five]{.alert} rows out\n- Japan has no matching region, Korea no matching GDP row, so both drop out\n- An inner join is a silent filter: if your row count falls after a join, this is usually why\n:::\n:::\n:::\n\n## LEFT JOIN\n### Keeping every row of the left table\n\n:::{style=\"margin-top: 15px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#39386a34 .cell cache='true' execution_count=17}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT g.country, r.region, g.gdp_per_capita\n    FROM gdp2020 AS g\n    LEFT JOIN regions AS r ON g.iso3 = r.iso3\n    ORDER BY g.country\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```\n┌───────────────┬───────────────┬────────────────┐\n│    country    │    region     │ gdp_per_capita │\n│    varchar    │    varchar    │     double     │\n├───────────────┼───────────────┼────────────────┤\n│ Brazil        │ Latin America │         8435.0 │\n│ China         │ East Asia     │        10573.0 │\n│ Germany       │ Europe        │        42373.0 │\n│ India         │ South Asia    │         1807.0 │\n│ Japan         │ NULL          │        35363.0 │\n│ United States │ North America │        59534.0 │\n└───────────────┴───────────────┴────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"48%\"}\n- The join you will use most often\n- [Six]{.alert} rows now: Japan is back, with `NULL` in `region`\n- The NULL means the join found no partner\n- `LEFT` is the table named in `FROM`. Swap the two tables and you get a different answer\n- Korea is still missing, because it only exists in the right table\n:::\n:::\n:::\n\n## FULL OUTER JOIN\n### Every row from both tables survives\n\n:::{style=\"margin-top: 12px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 21px;\"}\n\n::: {#06a9533b .cell cache='true' execution_count=18}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT g.country, r.iso3 AS region_iso3,\n           r.region, g.gdp_per_capita\n    FROM gdp2020 AS g\n    FULL OUTER JOIN regions AS r ON g.iso3 = r.iso3\n    ORDER BY r.region NULLS LAST\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\n┌───────────────┬─────────────┬───────────────┬────────────────┐\n│    country    │ region_iso3 │    region     │ gdp_per_capita │\n│    varchar    │   varchar   │    varchar    │     double     │\n├───────────────┼─────────────┼───────────────┼────────────────┤\n│ China         │ CHN         │ East Asia     │        10573.0 │\n│ NULL          │ KOR         │ East Asia     │           NULL │\n│ Germany       │ DEU         │ Europe        │        42373.0 │\n│ Brazil        │ BRA         │ Latin America │         8435.0 │\n│ United States │ USA         │ North America │        59534.0 │\n│ India         │ IND         │ South Asia    │         1807.0 │\n│ Japan         │ NULL        │ NULL          │        35363.0 │\n└───────────────┴─────────────┴───────────────┴────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"45%\"}\n:::{style=\"text-align: center; margin-top: -20px;\"}\n[![](figures/sql-joins.png){width=\"96%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/sql-joins.png\"}\n\n:::{style=\"font-size: 15px;\"}\nThe picture uses cut-down tables, so its counts are 3, 4 and 5. Ours give 5, 6 and 7\n:::\n:::\n\n:::{style=\"font-size: 17px; margin-top: 5px;\"}\n- Every row from both tables appears, with NULLs where the other side has no partner\n- [Seven]{.alert} rows: five matched, plus Korea (no GDP) and Japan (no region)\n- Just to recap: 5 rows from `INNER`, 6 from `LEFT`, 7 from `FULL OUTER`\n- To choose a join, ask which table must survive whole and what should happen to rows with no partner\n:::\n:::\n:::\n:::\n\n## Try it yourself! 🧠 {#sec-exercise-02}\n### Ten minutes\n\n:::{style=\"margin-top: 20px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\nHow rich is each region, and how much data is it based on?\n\n1. Use the `gdp2020` and `regions` tables from the joins section\n2. Report one row per region\n3. Count how many of that region's countries have a 2020 GDP figure\n4. Compute the mean GDP per capita of that region\n5. Keep every region, including the one with no GDP data at all\n6. Sort by mean GDP, highest first\n7. Send the region with no data to the bottom of the list\n\nOptional: list the codes that appear in only one of the two tables\n:::\n\n:::{.column width=\"48%\"}\nWhat to look for:\n\n- Which table goes on the left if every region must survive?\n- East Asia holds two codes and one GDP figure. `COUNT(*)` and `COUNT(g.country)` give different answers, and only one is right\n- What does `COUNT` do when the value is NULL?\n- Five regions come back, each with a count of 1\n- The optional part is a `FULL OUTER JOIN` with a `WHERE` on the NULLs\n\n:::{style=\"background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;\"}\nSolution and both outputs: [[Appendix 02]{.button}](#sec-appendix-02). Two more join tools, the anti-join and `UNION`: [[Appendix 06]{.button}](#sec-appendix-06)\n:::\n:::\n:::\n:::\n\n# SQL in Python 🐍 {background-color=\"#1B3A6B\"}\n\n## Querying a DataFrame by name\n### Your Python variable becomes a SQL table\n\n:::{style=\"margin-top: 15px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#e28c9a93 .cell cache='true' execution_count=19}\n``` {.python .cell-code}\nimport pandas as pd\n\ndf = pd.read_parquet(\n    \"../lecture-19/data/wdi_panel.parquet\"\n)\n\nduckdb.sql(\"SELECT COUNT(*) AS n FROM df\")\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```\n┌───────┐\n│   n   │\n│ int64 │\n├───────┤\n│ 59024 │\n└───────┘\n```\n:::\n:::\n\n\n:::\n\n- DuckDB finds `df` among your Python variables and reads it in place, with no copy and no registration step\n:::\n\n:::{.column width=\"48%\"}\n:::{style=\"text-align: center; margin-top: -15px;\"}\n[![](figures/duckdb-python-api-2026.png){width=\"92%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/duckdb-python-api-2026.png\"}\n\n:::{style=\"font-size: 17px;\"}\nSource: <https://duckdb.org/docs/stable/clients/python/overview>\n:::\n:::\n\n:::{style=\"background: rgba(230, 57, 70, 0.1); padding: 12px; border-radius: 10px; font-size: 18px; margin-top: 8px;\"}\n`country` is a pandas category, which DuckDB reads as an [enum]{.alert}. Add `::VARCHAR` when you want plain text in the result\n:::\n:::\n:::\n:::\n\n## Handing the result back to pandas\n### Turning a result into a DataFrame\n\n:::{style=\"margin-top: 12px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#5dd70d1b .cell cache='true' execution_count=20}\n``` {.python .cell-code}\nlong = duckdb.sql(\"\"\"\n    SELECT country::VARCHAR AS country, indicator,\n           ROUND(value, 1) AS value\n    FROM df\n    WHERE year = 2020\n      AND country IN ('Brazil', 'Germany', 'Japan')\n      AND indicator IN ('gdp_per_capita',\n                        'life_expectancy',\n                        'internet_users_pct')\n\"\"\").df()\n\nlong.pivot(index=\"country\", columns=\"indicator\",\n           values=\"value\")\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>indicator</th>\n      <th>gdp_per_capita</th>\n      <th>internet_users_pct</th>\n      <th>life_expectancy</th>\n    </tr>\n    <tr>\n      <th>country</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Brazil</th>\n      <td>8435.0</td>\n      <td>81.3</td>\n      <td>74.5</td>\n    </tr>\n    <tr>\n      <th>Germany</th>\n      <td>42372.9</td>\n      <td>89.8</td>\n      <td>81.0</td>\n    </tr>\n    <tr>\n      <th>Japan</th>\n      <td>35363.3</td>\n      <td>90.2</td>\n      <td>84.6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"45%\"}\n- [`.df()`]{.alert} turns a DuckDB result into a pandas DataFrame (`.pl()` gives a Polars one)\n- Nine rows come out of SQL, and pandas reshapes them into a 3 by 3 table\n- `pivot` has no short SQL equivalent, so this is a good place to hand over\n- Everything after `.df()` is ordinary pandas: `.plot()`, `.to_csv()`, `seaborn`, `statsmodels`\n- Moving between the two costs one method call\n- When to reach for SQL and when to stay in pandas: [[Appendix 07]{.button}](#sec-appendix-07)\n:::\n:::\n:::\n\n## Why sqlite3\n### Assignment 09 uses SQLite, and it ships with Python\n\n:::{style=\"margin-top: 15px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- [SQLite]{.alert} is a database in a single file, with no server\n  - The most deployed database in the world: every phone and every browser carries a copy\n- Python bundles it, so `import sqlite3` works on a machine with nothing installed\n- The cost is boilerplate DuckDB never asked for: a [connection]{.alert}, a [cursor]{.alert}, `commit()` and `fetchall()`\n  - A connection links your script to the database file. A cursor sends commands and collects results\n- The SQL itself barely changes. The next slides re-run queries you have already seen\n:::\n\n:::{.column width=\"48%\"}\n:::{style=\"text-align: center; margin-top: -10px;\"}\n[![](figures/sqlite-home-2026.png){width=\"100%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/sqlite-home-2026.png\"}\n\n:::{style=\"font-size: 17px;\"}\nSource: <https://sqlite.org>\n:::\n:::\n:::\n:::\n:::\n\n## Loading the panel into SQLite\n### Writing a DataFrame into a table\n\n:::{style=\"margin-top: 15px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#6677a13c .cell cache='true' execution_count=21}\n``` {.python .cell-code}\nimport sqlite3\n\n# \":memory:\" builds the database in RAM.\n# Use a filename such as \"wdi.db\" to keep it\nconn = sqlite3.connect(\":memory:\")\n\ndf.to_sql(\"wdi\", conn, index=False,\n          if_exists=\"replace\")\n\npd.read_sql(\"SELECT COUNT(*) AS n FROM wdi\", conn)\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>n</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>59024</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"45%\"}\n- [`to_sql`]{.alert} writes a DataFrame into a table and picks the column types for you\n- `index=False` stops the pandas index becoming a column called `index`\n- `if_exists=\"replace\"` drops any old table of that name, so the cell is safe to re-run\n- [`pd.read_sql`]{.alert} sends a query and returns a DataFrame, with no cursor and no `fetchall`\n- The load took 0.03 seconds for 59,024 rows on my laptop\n- Categories need no cast here, unlike the DuckDB enum\n:::\n:::\n:::\n\n## Connection, cursor, commit, fetch\n### The sqlite3 boilerplate\n\n:::{style=\"margin-top: 12px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"60%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#39395b0d .cell cache='true' execution_count=22}\n``` {.python .cell-code}\ncur = conn.cursor()\n\ncur.execute(\"\"\"CREATE TABLE regions\n               (iso3 TEXT PRIMARY KEY, region TEXT)\"\"\")\n\ncur.executemany(\"INSERT INTO regions VALUES (?, ?)\",\n    [(\"USA\", \"North America\"), (\"BRA\", \"Latin America\"),\n     (\"CHN\", \"East Asia\"),     (\"IND\", \"South Asia\"),\n     (\"DEU\", \"Europe\"),        (\"KOR\", \"East Asia\")])\nconn.commit()\n\ncur.execute(\"\"\"SELECT iso3, region FROM regions\n               WHERE region = ? ORDER BY iso3\"\"\",\n            (\"East Asia\",))\nprint(cur.fetchall())\n\ncur.execute(\"SELECT COUNT(*) FROM regions\")\nprint(cur.fetchone())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[('CHN', 'East Asia'), ('KOR', 'East Asia')]\n(6,)\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"40%\"}\n- [`executemany`]{.alert} runs one SQL template over a list of tuples\n- The [`?`]{.alert} marks a slot the driver fills in safely (Python's `None` becomes SQL's `NULL`)\n  - Never build a query with an f-string: that is how SQL injection happens\n- [`commit()`]{.alert} makes the writes permanent. Skip it and the inserts vanish when the script ends\n- [`fetchall()`]{.alert} returns a list of tuples, `fetchone()` a single tuple, e.g. `(6,)`\n- Parameters must be a tuple, hence the trailing comma in `(\"East Asia\",)`\n:::\n:::\n:::\n\n## The same queries, unchanged\n### Copy the SQL across and it runs\n\n:::{style=\"margin-top: 12px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"46%\"}\nThe `GROUP BY` by indicator:\n\n:::{style=\"font-size: 20px;\"}\n\n::: {#e98b3eac .cell cache='true' execution_count=23}\n``` {.python .cell-code}\npd.read_sql(\"\"\"\n    SELECT indicator,\n           COUNT(value) AS n,\n           ROUND(AVG(value), 2) AS mean_value\n    FROM wdi\n    WHERE year = 2020\n    GROUP BY indicator\n    ORDER BY indicator\n\"\"\", conn).head()\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>indicator</th>\n      <th>n</th>\n      <th>mean_value</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>co2_per_capita</td>\n      <td>203</td>\n      <td>4.45</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>fertility_rate</td>\n      <td>217</td>\n      <td>2.49</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>gdp_per_capita</td>\n      <td>208</td>\n      <td>16149.94</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>internet_users_pct</td>\n      <td>184</td>\n      <td>64.11</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>life_expectancy</td>\n      <td>217</td>\n      <td>72.50</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"54%\"}\nThe `CASE` income bands:\n\n:::{style=\"font-size: 20px;\"}\n\n::: {#f317525b .cell cache='true' execution_count=24}\n``` {.python .cell-code}\ncur.execute(\"\"\"\n    SELECT country, ROUND(value, 0) AS gdp_pc,\n        CASE\n            WHEN value IS NULL  THEN 'No data'\n            WHEN value >= 13846 THEN 'High income'\n            WHEN value >= 4466  THEN 'Upper middle'\n            WHEN value >= 1136  THEN 'Lower middle'\n            ELSE 'Low income'\n        END AS income_band\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita' AND year = 2020\n      AND country IN ('Norway', 'China', 'Burundi')\n    ORDER BY value DESC\n\"\"\")\ncur.fetchall()\n```\n\n::: {.cell-output .cell-output-display execution_count=23}\n```\n[('Norway', 78387.0, 'High income'),\n ('China', 10573.0, 'Upper middle'),\n ('Burundi', 263.0, 'Low income')]\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Where the two engines differ\n### DuckDB and SQLite side by side\n\n:::{style=\"margin-top: 12px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n:::{style=\"text-align: center; font-size: 18px;\"}\n| Feature | DuckDB | SQLite |\n|---|---|---|\n| `FROM 'file.parquet'` | works | no such table |\n| `ILIKE` | works | syntax error |\n| `SUMMARIZE` | works | syntax error |\n| `DESCRIBE SELECT ...` | works | use `PRAGMA table_info(t)` |\n| `SELECT 7 / 2` | `3.5` | `3` |\n| `LIKE 'united%'` | 0 rows | matches |\n| `SELECT * EXCLUDE (value)` | works | syntax error |\n| `GROUP BY ALL` | works | syntax error |\n| `STDDEV(x)` | works | no such function |\n| `INNER` / `LEFT` / `FULL OUTER JOIN` | works | works |\n| `CASE`, `COALESCE`, `IS NULL` | works | works |\n| Window functions, `MEDIAN`, `UNION` | works | works |\n:::\n:::\n\n:::{.column width=\"48%\"}\n- Sections 2 to 5 run unchanged on SQLite, apart from `ILIKE`, `SUMMARIZE`, `DESCRIBE` and reading a file by name\n- Two rows are traps, because they return an answer instead of an error:\n  - [`7 / 2`]{.alert} is 3.5 in DuckDB and 3 in SQLite (integer division). Write `7 * 1.0 / 2` in SQLite\n  - [`LIKE`]{.alert} is case-sensitive in DuckDB and case-insensitive (ASCII) in SQLite, so the same pattern returns different rows\n- SQLite has supported `RIGHT` and `FULL OUTER JOIN` since version 3.39 (2022). Older tutorials that emulate them are out of date\n- Every row tested on DuckDB 1.5.5 and SQLite 3.53.1\n:::\n:::\n:::\n\n## DuckDB on 200 million rows\n### The lecture 21 benchmark, revisited\n\n:::{style=\"margin-top: 20px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"55%\"}\n:::{style=\"text-align: center;\"}\n\n::: {#acc61f3b .cell cache='true' execution_count=25}\n\n::: {.cell-output .cell-output-display}\n![](22-sql-revision_files/figure-revealjs/cell-25-output-1.png){width=662 height=392}\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"45%\"}\n:::{style=\"font-size: 18px;\"}\n- Task: mean `value` by indicator and decade since 1990, on `wdi_big.parquet`, a synthetic panel of [200,681,600 rows]{.alert}\n- [DuckDB]{.alert}: 0.53 s. [Dask]{.alert}: 5.39 s. [pandas]{.alert}: 9.65 s\n- pandas loads every column into RAM. DuckDB reads only the row groups and columns the query names\n- Why: columnar layout, vectorised execution, all cores by default, and [predicate pushdown]{.alert} into the Parquet file\n- MacBook Pro, Apple M5, 10 cores, 24 GB RAM, macOS 26.6\n- One task on one machine: your seconds will differ, the ranking usually holds\n- [Polars]{.alert} is in the same range as DuckDB (see Tutorial 07 on the course website)\n- The query and the scripts behind it: [[Appendix 08]{.button}](#sec-appendix-08)\n:::\n:::\n:::\n:::\n\n# Summary {background-color=\"#1B3A6B\"}\n\n## What we learned today\n### The vocabulary, in the order we met it\n\n:::{style=\"margin-top: 20px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [SQL]{.alert} is declarative: you describe the answer and the engine plans the work\n- [DuckDB]{.alert} needs one import and reads a Parquet file or a pandas DataFrame by name\n- A [view]{.alert} names a query. `DESCRIBE` and `SUMMARIZE` show what is in it\n- [`WHERE`]{.alert} filters rows, [`GROUP BY`]{.alert} forms groups, [`HAVING`]{.alert} filters groups. No aggregate in `WHERE`\n- `COUNT(*)` minus `COUNT(value)` is the number of missing values\n:::\n\n:::{.column width=\"50%\"}\n- A [NULL]{.alert} means unknown. `COALESCE` fills one in, and a missing row needs a join instead\n- [`CASE`]{.alert} builds a category column. A [window function]{.alert} keeps every row and adds a group-level number\n- Joins: 5 rows from `INNER`, 6 from `LEFT`, 7 from `FULL OUTER` on the same two tables\n- [`sqlite3`]{.alert} needs a connection, a cursor, `commit()` and `fetchall()`, but the SQL is the same\n- On 200 million rows, DuckDB runs the same query in [0.53 seconds]{.alert}\n:::\n:::\n:::\n\n## Next class\n\n:::{style=\"margin-top: 25px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [Lecture 23]{.alert}: dependency management, virtual environments and containers\n- Today's queries depended on your Python, your DuckDB version and your laptop\n- Next class we package all three into an [image]{.alert} that a classmate, a server or a marker can run and get the same answer\n- `pip install duckdb` stops being a setup instruction and becomes a line in a `Dockerfile`\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"margin-top: -15px;\"}\nBefore then:\n\n1. Finish both exercises if you did not complete them in class\n2. Start [assignment 09]{.alert}, released today. It asks you to join two tables in SQLite\n3. Check that `import duckdb` and `import sqlite3` both work in your environment\n4. Skim [Tutorial 04](https://danilofreire.github.io/datasci350/04-duckdb-sql-tutorial.html) if any clause today felt new\n:::\n:::\n:::\n:::\n\n# Questions? 🤔 {background-color=\"#1B3A6B\"}\n\n# Thank you very much! 😊 {background-color=\"#1B3A6B\"}\n\n# Appendix 📚 {background-color=\"#1B3A6B\"}\n\n## Appendix 01: Solution to Exercise 01 {#sec-appendix-01}\n\n:::{style=\"margin-top: 20px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#ccd013f9 .cell cache='true' execution_count=26}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country,\n           ROUND(AVG(value), 1) AS mean_life_exp\n    FROM wdi\n    WHERE indicator = 'life_expectancy'\n      AND year >= 2010\n    GROUP BY country\n    HAVING AVG(value) > 82\n    ORDER BY mean_life_exp DESC\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```\n┌──────────────────────┬───────────────┐\n│       country        │ mean_life_exp │\n│       varchar        │    double     │\n├──────────────────────┼───────────────┤\n│ Monaco               │          85.5 │\n│ San Marino           │          84.4 │\n│ Hong Kong SAR, China │          84.3 │\n│ Andorra              │          83.8 │\n│ Japan                │          83.8 │\n└──────────────────────┴───────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"48%\"}\n- `WHERE` drops the rows before 2010 and every other indicator\n- `GROUP BY country` forms one group per country\n- `HAVING AVG(value) > 82` tests the group, so it cannot be written in `WHERE`\n- `ORDER BY` names `mean_life_exp`, the alias created in `SELECT`\n- Monaco, San Marino and Andorra are microstates with small, wealthy, ageing populations\n- Japan is the only country in the list with more than a million people\n\n[[Back to the exercise]{.button}](#sec-exercise-01)\n:::\n:::\n:::\n\n## Appendix 02: Solution to Exercise 02 {#sec-appendix-02}\n\n:::{style=\"margin-top: 15px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#2b56d7ee .cell cache='true' execution_count=27}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT r.region,\n           COUNT(g.country) AS countries_with_gdp,\n           ROUND(AVG(g.gdp_per_capita), 0) AS mean_gdp\n    FROM regions AS r\n    LEFT JOIN gdp2020 AS g ON g.iso3 = r.iso3\n    GROUP BY r.region\n    ORDER BY mean_gdp DESC NULLS LAST\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n```\n┌───────────────┬────────────────────┬──────────┐\n│    region     │ countries_with_gdp │ mean_gdp │\n│    varchar    │       int64        │  double  │\n├───────────────┼────────────────────┼──────────┤\n│ North America │                  1 │  59534.0 │\n│ Europe        │                  1 │  42373.0 │\n│ East Asia     │                  1 │  10573.0 │\n│ Latin America │                  1 │   8435.0 │\n│ South Asia    │                  1 │   1807.0 │\n└───────────────┴────────────────────┴──────────┘\n```\n:::\n:::\n\n\n:::\n\n- `regions` goes on the left because every region must survive\n- `COUNT(g.country)` skips the NULLs a left join produces. `COUNT(*)` would count Korea's empty row and report 2 for East Asia\n:::\n\n:::{.column width=\"50%\"}\nThe optional part:\n\n:::{style=\"font-size: 20px;\"}\n\n::: {#4b42b8c8 .cell cache='true' execution_count=28}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT COALESCE(g.iso3, r.iso3) AS iso3,\n           g.country, r.region\n    FROM gdp2020 AS g\n    FULL OUTER JOIN regions AS r ON g.iso3 = r.iso3\n    WHERE g.iso3 IS NULL OR r.iso3 IS NULL\n    ORDER BY iso3\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=27}\n```\n┌─────────┬─────────┬───────────┐\n│  iso3   │ country │  region   │\n│ varchar │ varchar │  varchar  │\n├─────────┼─────────┼───────────┤\n│ JPN     │ Japan   │ NULL      │\n│ KOR     │ NULL    │ East Asia │\n└─────────┴─────────┴───────────┘\n```\n:::\n:::\n\n\n:::\n\n- `COALESCE` picks up whichever code exists, because one of the two is always NULL here\n\n[[Back to the exercise]{.button}](#sec-exercise-02)\n:::\n:::\n:::\n\n## Appendix 03: When something goes wrong {#sec-appendix-03}\n\n:::{style=\"margin-top: 15px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n[`Parser Error: syntax error at or near \"..\"`]{.alert}\n\nThe file path is not quoted. Put single quotes around it: `FROM '../data/f.parquet'`.\n\n[`IO Error: No files found that match the pattern`]{.alert}\n\nThe path is quoted but wrong. Paths are relative to the folder you launched Python in, so check with `os.getcwd()`.\n\n[`Binder Error: Referenced column \"gdp\" not found`]{.alert}\n\nThe column name is misspelled or does not exist. Run `DESCRIBE SELECT * FROM wdi` and read the list.\n\n[`Parser Error: syntax error at or near \"SELCT\"`]{.alert}\n\nA keyword is misspelled. DuckDB quotes the offending word back at you, so read the message to the end\n:::\n\n:::{.column width=\"50%\"}\n[`Binder Error` on a value you know exists]{.alert}\n\nYou wrote `WHERE indicator = \"gdp_per_capita\"` with double quotes. Double quotes mean a column name in SQL, single quotes mean text.\n\n[`sqlite3.OperationalError: no such table: wdi`]{.alert}\n\nThe table was never created in this connection. `:memory:` databases vanish when the script ends, so re-run the `to_sql` cell.\n\n[`sqlite3.OperationalError: no such column: gdp`]{.alert}\n\nSame as the DuckDB binder error. List the columns with `PRAGMA table_info(wdi)`.\n\n[Your inserts disappeared]{.alert}\n\nYou forgot `conn.commit()`. SQLite holds writes in a transaction until you commit them\n:::\n:::\n:::\n\n## Appendix 04: The complete sqlite3 listing {#sec-appendix-04}\n\n<style>#sec-appendix-04 pre code { max-height: none; }</style>\n\n:::{style=\"margin-top: 12px; font-size: 15px;\"}\nEverything from the sqlite3 section in one script, ready to adapt for assignment 09:\n\n::: {#9bc49c5a .cell execution_count=29}\n``` {.python .cell-code}\nimport sqlite3\nimport pandas as pd\n\n# 1. Connect. Use a filename to keep the database on disk\nconn = sqlite3.connect(\"wdi.db\")\ncur = conn.cursor()\n\n# 2. Load a DataFrame into a table\ndf = pd.read_parquet(\"../lecture-19/data/wdi_panel.parquet\")\ndf.to_sql(\"wdi\", conn, index=False, if_exists=\"replace\")\n\n# 3. Create a table by hand and fill it\ncur.execute(\"DROP TABLE IF EXISTS regions\")\ncur.execute(\"CREATE TABLE regions (iso3 TEXT PRIMARY KEY, region TEXT)\")\ncur.executemany(\"INSERT INTO regions VALUES (?, ?)\",\n    [(\"USA\", \"North America\"), (\"BRA\", \"Latin America\"),\n     (\"CHN\", \"East Asia\"),     (\"IND\", \"South Asia\"),\n     (\"DEU\", \"Europe\"),        (\"KOR\", \"East Asia\")])\nconn.commit()\n\n# 4. Query with a cursor: fetchall returns a list of tuples\ncur.execute(\"SELECT iso3, region FROM regions WHERE region = ?\", (\"East Asia\",))\nprint(cur.fetchall())\n\n# 5. Query into pandas instead\nout = pd.read_sql(\"\"\"\n    SELECT r.region, COUNT(w.value) AS n, ROUND(AVG(w.value), 0) AS mean_gdp\n    FROM regions AS r\n    LEFT JOIN wdi AS w\n      ON w.iso3 = r.iso3\n     AND w.indicator = 'gdp_per_capita'\n     AND w.year = 2020\n    GROUP BY r.region\n    ORDER BY mean_gdp DESC\n\"\"\", conn)\nprint(out)\n\n# 6. Close the connection when you are done\nconn.close()\n```\n:::\n\n\n:::\n\n## Appendix 05: Grouping by two columns {#sec-appendix-05}\n### Every combination that exists in the data\n\n:::{style=\"margin-top: 15px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- Name two columns and you get one row for each pair that appears in the filtered rows\n- Two countries and two indicators give four rows here\n- Combinations with no rows never appear. SQL does not invent empty groups\n- Japan's mean life expectancy since 2010 is nine years above Brazil's. Its CO2 per person is almost four times higher\n- Aggregating a mean of yearly means like this weights every year equally. Say so when you report it\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#4fbcb1bb .cell cache='true' execution_count=30}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, indicator,\n           ROUND(AVG(value), 1) AS mean_value\n    FROM wdi\n    WHERE year >= 2010\n      AND country IN ('Brazil', 'Japan')\n      AND indicator IN ('life_expectancy',\n                        'co2_per_capita')\n    GROUP BY country, indicator\n    ORDER BY country, indicator\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=28}\n```\n┌─────────┬─────────────────┬────────────┐\n│ country │    indicator    │ mean_value │\n│ varchar │     varchar     │   double   │\n├─────────┼─────────────────┼────────────┤\n│ Brazil  │ co2_per_capita  │        2.4 │\n│ Brazil  │ life_expectancy │       74.8 │\n│ Japan   │ co2_per_capita  │        9.3 │\n│ Japan   │ life_expectancy │       83.8 │\n└─────────┴─────────────────┴────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Appendix 06: Anti-joins and UNION {#sec-appendix-06}\n### Finding rows with no partner\n\n:::{style=\"margin-top: 15px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- An [anti-join]{.alert} asks which rows on the left have no partner on the right\n- `NOT EXISTS` runs a small query for each row and keeps the row when it returns nothing\n\n:::{style=\"font-size: 20px;\"}\n\n::: {#02032e35 .cell cache='true' execution_count=31}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT g.country, g.iso3\n    FROM gdp2020 AS g\n    WHERE NOT EXISTS (\n        SELECT 1 FROM regions AS r\n        WHERE r.iso3 = g.iso3\n    )\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=29}\n```\n┌─────────┬─────────┐\n│ country │  iso3   │\n│ varchar │ varchar │\n├─────────┼─────────┤\n│ Japan   │ JPN     │\n└─────────┴─────────┘\n```\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"50%\"}\n- A join adds columns. [`UNION`]{.alert} stacks rows from two results that have the same columns\n- `UNION` removes duplicate rows, `UNION ALL` keeps them and is faster\n\n:::{style=\"font-size: 20px;\"}\n\n::: {#cf6d931b .cell cache='true' execution_count=32}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, 'rich' AS tag FROM gdp2020\n    WHERE gdp_per_capita > 30000\n    UNION\n    SELECT country, 'poor' AS tag FROM gdp2020\n    WHERE gdp_per_capita < 10000\n    ORDER BY country\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=30}\n```\n┌───────────────┬─────────┐\n│    country    │   tag   │\n│    varchar    │ varchar │\n├───────────────┼─────────┤\n│ Brazil        │ poor    │\n│ Germany       │ rich    │\n│ India         │ poor    │\n│ Japan         │ rich    │\n│ United States │ rich    │\n└───────────────┴─────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Appendix 07: When SQL beats a DataFrame {#sec-appendix-07}\n### A checklist for each tool\n\n:::{style=\"margin-top: 20px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\nReach for SQL when:\n\n- You are joining two or more tables\n- You are filtering and aggregating a file that is larger than your RAM\n- The question is a `GROUP BY` with a couple of conditions\n- Someone else has to read the query. A colleague who has never seen pandas can still read your `SELECT`\n- The data already lives in a database\n:::\n\n:::{.column width=\"50%\"}\nStay in pandas when:\n\n- You need row-by-row logic that has no set-based version\n- You are plotting, or feeding a model\n- You want many small inspectable steps, each one a variable you can look at\n- The reshaping is the hard part, as in the `pivot` in the SQL in Python section\n\n:::{style=\"background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;\"}\nWant more practice? The course website has a full self-study [DuckDB SQL tutorial](https://danilofreire.github.io/datasci350/04-duckdb-sql-tutorial.html) covering everything on these slides in more depth\n:::\n:::\n:::\n:::\n\n## Appendix 08: The benchmark query {#sec-appendix-08}\n### The query and where the timings come from\n\n:::{style=\"margin-top: 15px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- The DuckDB version is the query you already know, with a file path in `FROM` and a `GROUP BY` at the end\n- The data is `wdi_big.parquet`, a synthetic panel of 200,681,600 rows built by cloning the small panel many times\n- The file is not committed, and the script that rebuilds it is in [`data/make_big_parquet.py`](https://github.com/danilofreire/datasci350/blob/main/lectures/lecture-22/data/make_big_parquet.py)\n- The timings were measured once and saved to [`data/benchmark_results.csv`](https://raw.githubusercontent.com/danilofreire/datasci350/main/lectures/lecture-22/data/benchmark_results.csv). The deck reads that file rather than re-running anything\n- pandas loads the whole thing and calls `groupby`, Dask uses a parallel DataFrame, and DuckDB runs SQL straight over the file\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#2bf1a360 .cell execution_count=33}\n``` {.python .cell-code}\nimport duckdb\n\nduckdb.sql(\"\"\"\n    SELECT indicator,\n           (year // 10) * 10 AS decade,\n           AVG(value) AS mean_value\n    FROM 'data/wdi_big.parquet'\n    WHERE year >= 1990\n    GROUP BY indicator, decade\n\"\"\").df()\n```\n:::\n\n\n:::\n:::\n:::\n:::\n\n",
    "supporting": [
      "22-sql-revision_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}