<!DOCTYPE html>
<html lang="en-GB"><head>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Danilo Freire">
  <title>DATASCI 350 – DATASCI 350 - Data Science Computing</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-a43b6a543d407931682cae27ef33a0c9.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/multimodal/multimodal.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>
  
  <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">DATASCI 350 - Data Science Computing</h1>
  <p class="subtitle">Lecture 26 - Revision: Scaling, SQL and Containers</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Danilo Freire 
</div>
<div class="quarto-title-author-email">
<a href="mailto:danilo.freire@emory.edu">danilo.freire@emory.edu</a>
</div>
        <p class="quarto-title-affiliation">
            Department of Data and Decision Sciences <br> Emory University
          </p>
    </div>
</div>

</section>
<section>
<section id="hello-everyone" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Hello, everyone! 😊</h1>

</section>
<section id="where-we-are" class="slide level2">
<h2>Where we are</h2>
<h3 id="the-last-class-before-the-quiz-and-the-project">The last class before the quiz and the project</h3>
<div style="margin-top: 15px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>The eight modules, in the order we took them:
<ul>
<li><span class="alert">Introduction</span>: how a machine stores, encodes, and runs what you write</li>
<li><span class="alert">Command line and version control</span>: Bash, Git, and GitHub</li>
<li><span class="alert">Reproducible research</span>: Quarto, project structure, a pinned environment</li>
<li><span class="alert">AI-assisted programming</span>: local models, APIs, coding agents, RAG</li>
<li><span class="alert">Cloud computing</span>: EC2, S3, and a bill you can control</li>
<li><span class="alert">Getting data from the web</span>: APIs, JSON, and a committed snapshot</li>
<li><span class="alert">Scaling and performance</span>: joblib, Dask, DuckDB</li>
<li><span class="alert">Containers</span>: environments, Docker, and the image you hand in</li>
</ul></li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li>Today we revise the last two modules, because that is what the quiz covers</li>
<li><span class="alert">Quiz 05</span> is on Thursday 3 December and covers Lectures 21, 22, 23 and 25</li>
<li>The <span class="alert">final project</span> is due on Tuesday 8 December at 11:59pm, and must render inside a container</li>
<li>Your project can still use the first six modules, which this quiz does not cover</li>
</ul>
<div style="text-align: center; margin-top: 10px;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/table-reproducibility.jpg"><img data-src="figures/table-reproducibility.jpg" style="width:66.0%"></a></p>
<div style="font-size: 17px;">
<p>Source: <a href="https://book.the-turing-way.org/reproducible-research/overview/overview-definitions">The Turing Way Community (2025)</a></p>
</div>
</div>
</div></div>
</div>
</section>
<section id="lecture-overview" class="slide level2">
<h2>Lecture overview</h2>
<h3 id="what-we-will-cover-today">What we will cover today</h3>
<div style="margin-top: 15px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="alert">1. Scaling and performance</span></p>
<ul>
<li><code>map</code>, embarrassingly parallel work, <code>joblib</code></li>
<li>Big O, Amdahl’s law, and the GIL</li>
<li>Dask, and the 200-million-row benchmark</li>
</ul>
<p><span class="alert">2. SQL revision</span></p>
<ul>
<li>The order a query really runs in</li>
<li><code>WHERE</code> against <code>HAVING</code>, <code>COUNT(*)</code> against <code>COUNT(value)</code></li>
<li>Joins, <code>sqlite3</code>, and the dialect traps</li>
</ul>
</div><div class="column" style="width:50%;">
<p><span class="alert">3. SQL practice</span></p>
<ul>
<li>Four exercises on the World Bank panel</li>
<li>Twenty-five minutes, solutions in the appendix</li>
</ul>
<p><span class="alert">4. Containers and Docker</span></p>
<ul>
<li><code>venv</code>, conda and <code>uv</code> side by side</li>
<li>Images, containers, registries</li>
<li>The project checklist and the Q&amp;A</li>
</ul>
<p><span class="alert">5. Quiz 05 preparation</span></p>
<ul>
<li>What to expect from each lecture, and how to revise</li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="scaling-and-performance" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Scaling and performance ⚡</h1>

</section>
<section id="serial-and-parallel-work" class="slide level2">
<h2>Serial and parallel work</h2>
<h3 id="where-lecture-21-started">Where lecture 21 started</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><span class="alert">Serial</span>: each line finishes before the next one starts</li>
<li><span class="alert">Parallel</span>: independent tasks run at the same time on several cores</li>
<li><span class="alert"><code>map</code></span> applies one function to every element of a list
<ul>
<li>Every parallel tool copies that shape</li>
</ul></li>
<li>A problem is <span class="alert">embarrassingly parallel</span> when the tasks share no state and need no result from each other</li>
<li>Our <code>calculation()</code> on ten million random numbers qualified
<ul>
<li>A loop carrying a running total does not</li>
</ul></li>
<li>Four parallel calls never reached a full 4× saving: starting workers and moving results back costs time</li>
</ul>
</div><div class="column" style="width:48%;">
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a></a><span class="kw">def</span> bar(x):</span>
<span id="cb1-2"><a></a>    <span class="cf">return</span> x <span class="op">*</span> x</span>
<span id="cb1-3"><a></a></span>
<span id="cb1-4"><a></a>foo <span class="op">=</span> np.array([<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>])</span>
<span id="cb1-5"><a></a></span>
<span id="cb1-6"><a></a><span class="bu">list</span>(<span class="bu">map</span>(bar, foo))</span>
<span id="cb1-7"><a></a><span class="co"># [0, 1, 4, 9, 16, 25]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Before parallelising anything:
<ul>
<li>Are the tasks independent?</li>
<li>Is each one heavy enough to pay for starting a worker?</li>
</ul></li>
<li>If either answer is no, the cores will not help you</li>
</ul>
</div></div>
</div>
</section>
<section id="joblib-and-concurrent.futures" class="slide level2">
<h2>joblib and concurrent.futures</h2>
<h3 id="when-to-reach-for-each-one">When to reach for each one</h3>
<div style="margin-top: 15px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert"><code>joblib</code></span> turns a loop into parallel work in two lines
<ul>
<li><code>n_jobs=-1</code> uses every core</li>
</ul></li>
</ul>
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a></a><span class="im">from</span> joblib <span class="im">import</span> Parallel, delayed</span>
<span id="cb2-2"><a></a></span>
<span id="cb2-3"><a></a>results <span class="op">=</span> Parallel(n_jobs<span class="op">=</span><span class="dv">6</span>)(</span>
<span id="cb2-4"><a></a>    delayed(bar)(x) <span class="cf">for</span> x <span class="kw">in</span> foo</span>
<span id="cb2-5"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>sklearn</code> calls joblib internally whenever you set <code>n_jobs=-1</code></li>
<li><span class="alert"><code>concurrent.futures</code></span> ships with Python, so it works where you cannot install anything</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>The choice comes from why the task is slow:</li>
</ul>
<div style="text-align: center; font-size: 18px; margin-top: 10px; margin-bottom: 10px;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Your task</th>
<th>Tool</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number crunching</td>
<td><code>ProcessPoolExecutor</code></td>
<td>The processor is busy</td>
</tr>
<tr class="even">
<td>Downloading many URLs</td>
<td><code>ThreadPoolExecutor</code></td>
<td>The processor is idle, waiting</td>
</tr>
<tr class="odd">
<td>sklearn, numeric loops</td>
<td><code>joblib</code></td>
<td>Calls processes for you</td>
</tr>
<tr class="even">
<td>Bigger than RAM</td>
<td>Dask</td>
<td>Chunks the data itself</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><span class="alert">CPU-bound</span> work needs more processors</li>
<li><span class="alert">I/O-bound</span> work needs cheap threads that wait</li>
<li>Both executors copy the <code>map</code> interface: a function and an iterable</li>
</ul>
</div></div>
</div>
</section>
<section id="big-o" class="slide level2">
<h2>Big O</h2>
<h3 id="how-the-runtime-grows-with-the-input">How the runtime grows with the input</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><span class="alert">Big O</span> describes how the runtime grows as the input grows</li>
<li><span class="alert">O(1)</span> constant, <span class="alert">O(n)</span> linear, <span class="alert">O(n²)</span> quadratic: doubling the input costs nothing, twice as much, or four times as much</li>
<li>With <code>p</code> cores, an O(n) problem becomes <span class="alert">O(n/p + overhead)</span></li>
<li>Parallelism divides the constant in front of the class, and never the class itself</li>
<li><code>pairwise_sum</code> on 1,000 elements is a million operations, and 10 billion at 100,000
<ul>
<li>No core count rescues that</li>
</ul></li>
<li>An O(n log n) algorithm beats a parallelised O(n²) one on any interesting input</li>
</ul>
</div><div class="column" style="width:48%;">
<div style="font-size: 20px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a></a><span class="co"># O(n^2): every pair of elements</span></span>
<span id="cb3-2"><a></a><span class="kw">def</span> pairwise_sum(data):</span>
<span id="cb3-3"><a></a>    n <span class="op">=</span> <span class="bu">len</span>(data)</span>
<span id="cb3-4"><a></a>    results <span class="op">=</span> []</span>
<span id="cb3-5"><a></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n):</span>
<span id="cb3-6"><a></a>        <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n):</span>
<span id="cb3-7"><a></a>            results.append(data[i] <span class="op">+</span> data[j])</span>
<span id="cb3-8"><a></a>    <span class="cf">return</span> results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Poor candidates for parallelism:
<ul>
<li>Steps that depend on the previous result</li>
<li>Algorithms with shared state</li>
<li>Work limited by memory rather than by the CPU</li>
</ul></li>
</ul>
</div></div>
</div>
</section>
<section id="amdahls-law" class="slide level2">
<h2>Amdahl’s law</h2>
<h3 id="the-serial-share-caps-your-speed-up">The serial share caps your speed-up</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>Every program has a <span class="alert">serial share</span>: the setup, the merging of the results, and any step that waits for the one before it</li>
<li>The formula is <span class="math inline">\(\text{speedup} = \dfrac{1}{s + \dfrac{p}{N}}\)</span>, with <span class="math inline">\(s\)</span> the serial fraction, <span class="math inline">\(p = 1 - s\)</span> the parallel fraction, and <span class="math inline">\(N\)</span> the number of cores</li>
<li>A program that is 90% parallel, on 8 cores:</li>
</ul>
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb4-1"><a></a>s = 0.1        p = 0.9        N = 8</span>
<span id="cb4-2"><a></a></span>
<span id="cb4-3"><a></a>1 / (0.1 + 0.9/8)</span>
<span id="cb4-4"><a></a>  = 1 / (0.1 + 0.1125)</span>
<span id="cb4-5"><a></a>  = 1 / 0.2125</span>
<span id="cb4-6"><a></a>  = 4.7x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:48%;">
<ul>
<li>Eight cores give 4.7×: half the hardware does nothing for you</li>
<li>Push <span class="math inline">\(N\)</span> to infinity and the ceiling is <span class="math inline">\(1/s\)</span>, which is 10× here</li>
<li>A 50% serial program never passes 2×, however large the cluster</li>
<li>Measure before you scale: <code>%timeit</code> and <code>cProfile</code> tell you what <span class="math inline">\(s\)</span> actually is</li>
<li>Expect this arithmetic in the quiz</li>
</ul>
</div></div>
</div>
</section>
<section id="the-gil" class="slide level2">
<h2>The GIL</h2>
<h3 id="why-one-thread-runs-python-at-a-time">Why one thread runs Python at a time</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>CPython has a <span class="alert">Global Interpreter Lock</span>: one thread runs Python code at a time, however many cores you own</li>
<li>Threads still help while your code <span class="alert">waits</span>, because the lock is released during a download or a disk read</li>
<li>Threads do nothing while your code <span class="alert">computes</span>, because the lock keeps the others idle</li>
<li>CPU-bound work needs <span class="alert">processes</span>, each one a separate Python with its own lock</li>
<li>NumPy, Polars and DuckDB <span class="alert">release the GIL</span> while their C and Rust code runs, so they use every core with no processes to manage</li>
<li>A <span class="alert">free-threaded build</span> is official since Python 3.14, and it is not the default</li>
</ul>
</div><div class="column" style="width:48%;">
<div style="text-align: center; font-size: 18px; margin-top: 15px;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Task</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Number crunching</td>
<td>Processes</td>
</tr>
<tr class="even">
<td>Downloading many URLs</td>
<td>Threads</td>
</tr>
<tr class="odd">
<td>NumPy, Polars, DuckDB</td>
<td>Either or neither</td>
</tr>
<tr class="even">
<td><code>sklearn</code> with <code>n_jobs=-1</code></td>
<td>Processes, via joblib</td>
</tr>
</tbody>
</table>
</div>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 15px;">
<p>The quiz will ask you to pick one. Start from the lock: it is released while Python waits and held while Python computes</p>
</div>
</div></div>
</div>
</section>
<section id="dask" class="slide level2">
<h2>Dask</h2>
<h3 id="lazy-evaluation-and-when-a-cluster-is-worth-it">Lazy evaluation, and when a cluster is worth it</h3>
<div style="margin-top: 15px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><span class="alert">Dask</span> gives you lazy versions of tools you already use: <span class="alert">Array</span> for NumPy, <span class="alert">DataFrame</span> for pandas, <span class="alert"><code>delayed</code></span> for your own functions, <span class="alert">Distributed</span> for a cluster</li>
<li><span class="alert">Lazy</span> means nothing runs until <code>.compute()</code>, and until then you are building a task graph</li>
<li>The graph lets Dask optimise the plan and keep memory down before any work starts</li>
<li><code>.persist()</code> computes a result once and holds it in RAM
<ul>
<li>Use it on a small aggregate, never on the raw frame</li>
</ul></li>
<li><code>joblib</code> parallelises your functions and leaves the data alone</li>
<li>Dask <span class="alert">chunks the data itself</span>, so a frame can be larger than your RAM</li>
<li>The <span class="alert">dashboard</span> at <code>localhost:8787</code> shows the task stream live, and white space in a row means an idle worker</li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li>A cluster pays for itself when the data does not fit on the machine, or when the graph has real dependencies between tasks</li>
<li>When the data fits in memory it costs you: building the graph and moving chunks can make Dask slower than pandas</li>
<li><span class="alert">Parquet</span> cut our January 2000 data from 182 MB to 86 MB and made the group-by much faster</li>
</ul>
<div style="text-align: center; margin-top: 10px;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/distributed.png"><img data-src="figures/distributed.png" style="width:78.0%"></a></p>
</div>
</div></div>
</div>
</section>
<section id="which-tool-when" class="slide level2">
<h2>Which tool when</h2>
<h3 id="the-same-group-by-on-pandas-dask-and-duckdb">The same group-by on pandas, Dask and DuckDB</h3>
<div style="margin-top: 12px; font-size: 19px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>The task from lecture 22: mean <code>value</code> by indicator and decade, on a synthetic panel of <span class="alert">200,681,600 rows</span></li>
</ul>
<div style="text-align: center; font-size: 19px; margin-top: 10px; margin-bottom: 10px;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Engine</th>
<th>Time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>pandas</td>
<td>9.65 s</td>
</tr>
<tr class="even">
<td>Dask</td>
<td>5.39 s</td>
</tr>
<tr class="odd">
<td>DuckDB</td>
<td>0.53 s</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>MacBook Pro, Apple M5, 10 cores, 24 GB RAM</li>
<li>pandas holds every column in RAM</li>
<li>DuckDB reads only the row groups and columns the query names</li>
<li>The gap comes from a columnar layout, vectorised execution, every core by default, and <span class="alert">predicate pushdown</span> into the Parquet file</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="text-align: center; margin-bottom: 10px; font-size: 19px;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Your situation</th>
<th>Reach for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fits in RAM, exploring, plotting</td>
<td>pandas</td>
</tr>
<tr class="even">
<td>A single large file on one machine</td>
<td>Polars or DuckDB</td>
</tr>
<tr class="odd">
<td>Bigger than the machine, or a real cluster</td>
<td>Dask</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>This benchmark measures a single task on one machine
<ul>
<li>Your seconds will differ, and the ranking usually holds</li>
</ul></li>
<li>Measure where the time goes before you scale anything</li>
</ul>
<div style="text-align: center; margin-top: 8px;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/duckdb-db-benchmark-2026-crop.png"><img data-src="figures/duckdb-db-benchmark-2026-crop.png" style="width:80.0%"></a></p>
<div style="font-size: 17px;">
<p>Source: <a href="https://duckdblabs.github.io/db-benchmark/">db-benchmark</a></p>
</div>
</div>
</div></div>
</div>
</section></section>
<section>
<section id="sql-revision" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>SQL revision 🦆</h1>

</section>
<section id="the-order-a-query-really-runs-in" class="slide level2">
<h2>The order a query really runs in</h2>
<h3 id="how-the-engine-evaluates-a-query">How the engine evaluates a query</h3>
<div style="margin-top: 10px; font-size: 20px;">
<div style="text-align: center;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/sql-evaluation-order.png"><img data-src="figures/sql-evaluation-order.png" style="width:62.0%"></a></p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>You write <code>SELECT</code> first, but the engine runs it fifth</li>
<li><code>FROM</code> finds the rows, <code>WHERE</code> filters them, <code>GROUP BY</code> forms the groups, <code>HAVING</code> filters the groups, and <code>SELECT</code> computes the output columns</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>This ladder answers most SQL questions in the quiz, including why an aggregate cannot go in <code>WHERE</code></li>
<li>DuckDB and SQLite let you reuse a <code>SELECT</code> alias in <code>WHERE</code>
<ul>
<li>PostgreSQL rejects it, so do not rely on it</li>
</ul></li>
</ul>
</div></div>
</div>
</section>
<section id="where-and-having" class="slide level2">
<h2>WHERE and HAVING</h2>
<h3 id="which-clause-filters-what">Which clause filters what</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert"><code>WHERE</code></span> filters rows before grouping</li>
<li><span class="alert"><code>HAVING</code></span> filters groups afterwards</li>
<li>“Which years count?” is a row question, and “Which countries qualify?” is a group question</li>
<li>No aggregate belongs in <code>WHERE</code>, because at that point the groups do not exist yet</li>
<li>Every column in your <code>SELECT</code> is either in the <code>GROUP BY</code> or inside an aggregate function</li>
<li><code>ORDER BY</code> can name an alias you created in <code>SELECT</code>, which <code>mean_gdp</code> does here</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource sql number-lines code-with-copy"><code class="sourceCode sql"><span id="cb5-1"><a></a><span class="kw">SELECT</span> country,</span>
<span id="cb5-2"><a></a>       <span class="fu">ROUND</span>(<span class="fu">AVG</span>(<span class="fu">value</span>), <span class="dv">0</span>) <span class="kw">AS</span> mean_gdp</span>
<span id="cb5-3"><a></a><span class="kw">FROM</span> wdi</span>
<span id="cb5-4"><a></a><span class="kw">WHERE</span> <span class="kw">indicator</span> <span class="op">=</span> <span class="st">'gdp_per_capita'</span></span>
<span id="cb5-5"><a></a>  <span class="kw">AND</span> <span class="dt">year</span> <span class="op">&gt;=</span> <span class="dv">2010</span></span>
<span id="cb5-6"><a></a><span class="kw">GROUP</span> <span class="kw">BY</span> country</span>
<span id="cb5-7"><a></a><span class="kw">HAVING</span> <span class="fu">AVG</span>(<span class="fu">value</span>) <span class="op">&gt;</span> <span class="dv">60000</span></span>
<span id="cb5-8"><a></a><span class="kw">ORDER</span> <span class="kw">BY</span> mean_gdp <span class="kw">DESC</span></span>
<span id="cb5-9"><a></a><span class="kw">LIMIT</span> <span class="dv">5</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>WHERE year &gt;= 2010</code> drops old rows</li>
<li><code>HAVING AVG(value) &gt; 60000</code> drops poorer countries</li>
<li>Small economies with financial centres win this list: Monaco, Liechtenstein and Bermuda all have fewer than 100,000 people</li>
</ul>
</div></div>
</div>
</section>
<section id="count-and-countvalue" class="slide level2">
<h2>COUNT(*) and COUNT(value)</h2>
<h3 id="counting-rows-and-counting-values">Counting rows and counting values</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert"><code>COUNT(*)</code></span> counts rows</li>
<li><span class="alert"><code>COUNT(value)</code></span> counts the rows where <code>value</code> is present</li>
<li>The difference between the two is the number of missing values</li>
<li>217 countries have a GDP row for 2020, and only 208 have a number in it</li>
<li><code>AVG</code>, <code>SUM</code>, <code>MIN</code> and <code>MAX</code> all skip missing values silently, so a mean can hide a column that is half empty</li>
<li><code>primary_enrolment_net</code> has 217 rows in 2020 and no numbers at all, so <code>COUNT(value)</code> is 0 and <code>AVG</code> is NULL</li>
</ul>
</div><div class="column" style="width:50%;">
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource sql number-lines code-with-copy"><code class="sourceCode sql"><span id="cb6-1"><a></a><span class="kw">SELECT</span> <span class="dt">year</span>,</span>
<span id="cb6-2"><a></a>       <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="kw">AS</span> n_rows,</span>
<span id="cb6-3"><a></a>       <span class="fu">COUNT</span>(<span class="fu">value</span>) <span class="kw">AS</span> with_value,</span>
<span id="cb6-4"><a></a>       <span class="fu">COUNT</span>(<span class="op">*</span>) <span class="op">-</span> <span class="fu">COUNT</span>(<span class="fu">value</span>) <span class="kw">AS</span> missing</span>
<span id="cb6-5"><a></a><span class="kw">FROM</span> wdi</span>
<span id="cb6-6"><a></a><span class="kw">WHERE</span> <span class="kw">indicator</span> <span class="op">=</span> <span class="st">'internet_users_pct'</span></span>
<span id="cb6-7"><a></a>  <span class="kw">AND</span> <span class="dt">year</span> <span class="kw">IN</span> (<span class="dv">1990</span>, <span class="dv">2000</span>, <span class="dv">2020</span>)</span>
<span id="cb6-8"><a></a><span class="kw">GROUP</span> <span class="kw">BY</span> <span class="dt">year</span></span>
<span id="cb6-9"><a></a><span class="kw">ORDER</span> <span class="kw">BY</span> <span class="dt">year</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Internet use is recorded for 217 countries in each of those years, with 9 numbers missing in 1990, 21 in 2000, and 33 in 2020</li>
<li>Coverage gets <span class="alert">worse</span> over time: small territories join the panel and never report the series
<ul>
<li>Small territories join the panel and never report the series</li>
</ul></li>
</ul>
</div></div>
</div>
</section>
<section id="the-three-joins" class="slide level2">
<h2>The three joins</h2>
<h3 id="which-rows-survive-the-join">Which rows survive the join</h3>
<div style="margin-top: 10px; font-size: 20px;">
<div style="text-align: center;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/sql-joins.png"><img data-src="figures/sql-joins.png" style="width:50.0%"></a></p>
</div>
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><span class="alert"><code>INNER JOIN</code></span> keeps the rows that match on both sides
<ul>
<li>A silent filter: a row count that drops after a join usually means this</li>
</ul></li>
<li><span class="alert"><code>LEFT JOIN</code></span> keeps the left table whole and fills the missing side with NULL
<ul>
<li>That NULL is the join telling you it found no partner</li>
</ul></li>
<li><span class="alert"><code>FULL OUTER JOIN</code></span> keeps everything from both sides</li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li>In lecture 22 the same two tiny tables gave 5, 6 and 7 rows</li>
<li><code>ON</code> says which columns must agree, and the table aliases keep <code>g.iso3</code> and <code>r.iso3</code> apart</li>
<li>Which table must survive whole, and what should happen to a row with no partner?</li>
</ul>
</div></div>
</div>
</section>
<section id="sqlite3-in-one-slide" class="slide level2">
<h2>sqlite3 in one slide</h2>
<h3 id="connection-cursor-commit-fetch">Connection, cursor, commit, fetch</h3>
<div style="margin-top: 12px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:58%;">
<div style="font-size: 20px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a></a><span class="im">import</span> sqlite3</span>
<span id="cb7-2"><a></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-3"><a></a></span>
<span id="cb7-4"><a></a>conn <span class="op">=</span> sqlite3.<span class="ex">connect</span>(<span class="st">":memory:"</span>)   <span class="co"># or "wdi.db"</span></span>
<span id="cb7-5"><a></a>cur <span class="op">=</span> conn.cursor()</span>
<span id="cb7-6"><a></a></span>
<span id="cb7-7"><a></a>df.to_sql(<span class="st">"wdi"</span>, conn, index<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb7-8"><a></a>          if_exists<span class="op">=</span><span class="st">"replace"</span>)</span>
<span id="cb7-9"><a></a></span>
<span id="cb7-10"><a></a>cur.execute(<span class="st">"""CREATE TABLE regions</span></span>
<span id="cb7-11"><a></a><span class="st">               (iso3 TEXT PRIMARY KEY, region TEXT)"""</span>)</span>
<span id="cb7-12"><a></a>cur.executemany(<span class="st">"INSERT INTO regions VALUES (?, ?)"</span>,</span>
<span id="cb7-13"><a></a>    [(<span class="st">"USA"</span>, <span class="st">"North America"</span>), (<span class="st">"KOR"</span>, <span class="st">"East Asia"</span>)])</span>
<span id="cb7-14"><a></a>conn.commit()</span>
<span id="cb7-15"><a></a></span>
<span id="cb7-16"><a></a>cur.execute(<span class="st">"SELECT * FROM regions WHERE region = ?"</span>,</span>
<span id="cb7-17"><a></a>            (<span class="st">"East Asia"</span>,))</span>
<span id="cb7-18"><a></a><span class="bu">print</span>(cur.fetchall())</span>
<span id="cb7-19"><a></a></span>
<span id="cb7-20"><a></a>out <span class="op">=</span> pd.read_sql(<span class="st">"SELECT COUNT(*) FROM wdi"</span>, conn)</span>
<span id="cb7-21"><a></a>conn.close()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:42%;">
<ul>
<li>DuckDB never made you write a <span class="alert">connection</span>, a <span class="alert">cursor</span>, a <code>commit()</code> or a <code>fetchall()</code></li>
<li><span class="alert"><code>to_sql</code></span> writes a DataFrame into a table and picks the column types for you</li>
<li>The <span class="alert"><code>?</code></span> marks a slot the driver fills in safely, and it takes a tuple
<ul>
<li>The trailing comma in <code>("East Asia",)</code> is what makes it one</li>
</ul></li>
<li>Never build a query with an f-string, which is how SQL injection happens</li>
<li><span class="alert"><code>commit()</code></span> makes writes permanent, and skipping it loses your inserts when the script ends</li>
<li><span class="alert"><code>pd.read_sql</code></span> sends a query and hands back a DataFrame, with no cursor involved</li>
</ul>
</div></div>
</div>
</section>
<section id="where-the-two-engines-differ" class="slide level2">
<h2>Where the two engines differ</h2>
<h3 id="the-rows-that-give-an-answer-instead-of-an-error">The rows that give an answer instead of an error</h3>
<div style="margin-top: 12px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:50%;">
<div style="text-align: center; font-size: 17px;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Feature</th>
<th>DuckDB</th>
<th>SQLite</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>FROM 'file.parquet'</code></td>
<td>works</td>
<td>no such table</td>
</tr>
<tr class="even">
<td><code>ILIKE</code></td>
<td>works</td>
<td>syntax error</td>
</tr>
<tr class="odd">
<td><code>SUMMARIZE</code></td>
<td>works</td>
<td>syntax error</td>
</tr>
<tr class="even">
<td><code>DESCRIBE SELECT ...</code></td>
<td>works</td>
<td><code>PRAGMA table_info(t)</code></td>
</tr>
<tr class="odd">
<td><code>SELECT 7 / 2</code></td>
<td><code>3.5</code></td>
<td><code>3</code></td>
</tr>
<tr class="even">
<td><code>LIKE 'united%'</code></td>
<td>0 rows</td>
<td>matches</td>
</tr>
<tr class="odd">
<td><code>GROUP BY ALL</code></td>
<td>works</td>
<td>syntax error</td>
</tr>
<tr class="even">
<td><code>STDDEV(x)</code></td>
<td>works</td>
<td>no such function</td>
</tr>
<tr class="odd">
<td><code>INNER</code> / <code>LEFT</code> / <code>FULL OUTER</code></td>
<td>works</td>
<td>works</td>
</tr>
<tr class="even">
<td><code>CASE</code>, <code>COALESCE</code>, <code>IS NULL</code></td>
<td>works</td>
<td>works</td>
</tr>
<tr class="odd">
<td>Window functions, <code>UNION</code></td>
<td>works</td>
<td>works</td>
</tr>
</tbody>
</table>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Most of the language is identical, and two rows are traps:
<ul>
<li><span class="alert"><code>7 / 2</code></span> is 3.5 in DuckDB and 3 in SQLite, because integer division is the default there, so write <code>7 * 1.0 / 2</code> for the decimal</li>
<li><span class="alert"><code>LIKE</code></span> is case-sensitive in DuckDB and case-insensitive for ASCII in SQLite, so the same pattern quietly returns different rows</li>
</ul></li>
<li>SQLite has done <code>RIGHT</code> and <code>FULL OUTER JOIN</code> natively since version 3.39, released in 2022</li>
<li>Every row was tested on DuckDB 1.5.5 and SQLite 3.53.1</li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="sql-practice" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>SQL practice 🧠</h1>

</section>
<section id="the-setup-for-all-four-exercises" class="slide level2">
<h2>The setup for all four exercises</h2>
<h3 id="what-to-run-before-exercise-1">What to run before exercise 1</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Open a notebook or a Python file next to the lecture folder, and run this once:</li>
</ul>
<div style="font-size: 22px;">
<div id="82dd019e" class="cell" data-cache="true" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a></a><span class="im">import</span> duckdb</span>
<span id="cb8-2"><a></a></span>
<span id="cb8-3"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb8-4"><a></a><span class="st">    CREATE OR REPLACE VIEW wdi AS</span></span>
<span id="cb8-5"><a></a><span class="st">    SELECT * FROM</span></span>
<span id="cb8-6"><a></a><span class="st">    '../lecture-19/data/wdi_panel.parquet'</span></span>
<span id="cb8-7"><a></a><span class="st">"""</span>)</span>
<span id="cb8-8"><a></a></span>
<span id="cb8-9"><a></a>duckdb.sql(<span class="st">"SELECT COUNT(*) AS n_rows FROM wdi"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>┌────────┐
│ n_rows │
│ int64  │
├────────┤
│  59024 │
└────────┘</code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>The same panel from Module 06: 59,024 rows of <code>country</code>, <code>iso3</code>, <code>indicator</code>, <code>year</code> and <code>value</code></li>
<li>Eight indicators, including <code>gdp_per_capita</code>, <code>life_expectancy</code>, <code>co2_per_capita</code> and <code>internet_users_pct</code></li>
<li>The four exercises get harder as we go, and each one has a solution appendix</li>
<li>Work in pairs if you like
<ul>
<li>I will walk around, and we look at each solution together</li>
</ul></li>
<li>Exercise 4 needs <code>import sqlite3</code> and <code>import pandas as pd</code> as well</li>
</ul>
</div></div>
</div>
</section>
<section id="sec-exercise-01" class="slide level2 scrollable">
<h2>Try it yourself! 🧠</h2>
<h3 id="five-minutes">Five minutes</h3>
<div style="margin-top: 20px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<p>Which countries emitted the most CO2 per person in 2020?</p>
<ol type="1">
<li>Run the setup cell so the <code>wdi</code> view exists</li>
<li>Keep only the rows for <code>co2_per_capita</code></li>
<li>Keep only the year 2020</li>
<li>Return <code>country</code> and <code>value</code>, rounded to one decimal</li>
<li>Rename the rounded column <code>co2_pc</code></li>
<li>Sort from highest to lowest</li>
<li>Return the top five rows</li>
</ol>
</div><div class="column" style="width:48%;">
<p>What to look for:</p>
<ul>
<li>Two conditions join with <code>AND</code> inside one <code>WHERE</code></li>
<li>Text goes in <span class="alert">single quotes</span>
<ul>
<li>Double quotes mean a column name, and DuckDB will say the column does not exist</li>
</ul></li>
<li>Sorting needs <code>DESC</code>, because <code>ASC</code> is the default</li>
<li>The winner is a Pacific island with fewer than 20,000 people</li>
<li>Four of the five are oil or gas economies</li>
</ul>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;">
<p>Solution and the full output: <a href="#/sec-appendix-01"><span class="button">Appendix 01</span></a></p>
</div>
</div></div>
</div>
</section>
<section id="sec-exercise-02" class="slide level2 scrollable">
<h2>Try it yourself! 🧠</h2>
<h3 id="five-minutes-1">Five minutes</h3>
<div style="margin-top: 20px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<p>Which countries have been the most connected since 2015?</p>
<ol type="1">
<li>Keep only the rows for <code>internet_users_pct</code></li>
<li>Keep only the years from 2015 onwards</li>
<li>Report one row per country</li>
<li>Count how many years have a number in <code>value</code>, and call it <code>n_years</code></li>
<li>Compute the mean of <code>value</code>, rounded to one decimal, as <code>mean_internet</code></li>
<li>Keep the countries with at least 5 years of data and a mean above 95</li>
<li>Sort by the mean, highest first, and return five rows</li>
</ol>
</div><div class="column" style="width:48%;">
<p>What to look for:</p>
<ul>
<li>The filter on <code>year</code> and the two filters on the group go in <span class="alert">different clauses</span></li>
<li><code>COUNT(value)</code> and <code>COUNT(*)</code> disagree here, and only one of them counts years with data</li>
<li>Five countries come back, every one of them above 97%</li>
<li>The list mixes Nordic countries with Gulf states, and one country is neither</li>
<li>An error about an aggregate in <code>WHERE</code> means the evaluation ladder is worth another look</li>
</ul>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;">
<p>Solution and the full output: <a href="#/sec-appendix-02"><span class="button">Appendix 02</span></a></p>
</div>
</div></div>
</div>
</section>
<section id="sec-exercise-03" class="slide level2 scrollable">
<h2>Try it yourself! 🧠</h2>
<h3 id="eight-minutes">Eight minutes</h3>
<div style="margin-top: -14px; font-size: 16px;">
<div class="columns">
<div class="column" style="width:60%;">
<div style="margin-top: -12px;">
<p>How rich is each region, and on how much data? Run this first.</p>
</div>
<ol type="1">
<li>Report one row per region, keeping every region</li>
<li>Count the countries in the region with a 2022 GDP figure</li>
<li>Compute the region’s mean GDP per capita</li>
<li>Sort by the mean, highest first, empty region last</li>
</ol>
<div style="font-size: 20px; margin-top: -10px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb10-2"><a></a><span class="st">    CREATE OR REPLACE TABLE gdp2022 AS</span></span>
<span id="cb10-3"><a></a><span class="st">    SELECT country, iso3, ROUND(value, 0) AS gdp_per_capita</span></span>
<span id="cb10-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb10-5"><a></a><span class="st">    WHERE indicator = 'gdp_per_capita' AND year = 2022</span></span>
<span id="cb10-6"><a></a><span class="st">      AND iso3 IN ('USA','BRA','CHN','IND','NGA','FRA')</span></span>
<span id="cb10-7"><a></a><span class="st">"""</span>)</span>
<span id="cb10-8"><a></a></span>
<span id="cb10-9"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb10-10"><a></a><span class="st">    CREATE OR REPLACE TABLE regions</span></span>
<span id="cb10-11"><a></a><span class="st">        (iso3 VARCHAR PRIMARY KEY, region VARCHAR)</span></span>
<span id="cb10-12"><a></a><span class="st">"""</span>)</span>
<span id="cb10-13"><a></a></span>
<span id="cb10-14"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb10-15"><a></a><span class="st">    INSERT INTO regions VALUES</span></span>
<span id="cb10-16"><a></a><span class="st">        ('USA', 'North America'), ('BRA', 'Latin America'),</span></span>
<span id="cb10-17"><a></a><span class="st">        ('CHN', 'East Asia'),     ('JPN', 'East Asia'),</span></span>
<span id="cb10-18"><a></a><span class="st">        ('IND', 'South Asia'),    ('FRA', 'Europe'),</span></span>
<span id="cb10-19"><a></a><span class="st">        ('ZAF', 'Sub-Saharan Africa')</span></span>
<span id="cb10-20"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:40%;">
<p>What to look for:</p>
<ul>
<li>Which table goes on the left if every region must survive?</li>
<li>East Asia holds two codes and one GDP figure, Sub-Saharan Africa one code and none</li>
<li><code>COUNT(*)</code> reports 2 and 1 there, <code>COUNT(g.country)</code> reports 1 and 0</li>
<li>Six regions come back, and one of them has a NULL mean</li>
<li>Nigeria has a GDP figure and no region, so it never appears
<ul>
<li>Swap the two table names and it does</li>
</ul></li>
</ul>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 10px;">
<p>Solution and both counts: <a href="#/sec-appendix-03"><span class="button">Appendix 03</span></a></p>
</div>
</div></div>
</div>
</section>
<section id="sec-exercise-04" class="slide level2 scrollable">
<h2>Try it yourself! 🧠</h2>
<h3 id="seven-minutes">Seven minutes</h3>
<div style="margin-top: 15px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:52%;">
<p>Run exercise 2 again, in <code>sqlite3</code> this time.</p>
<ol type="1">
<li>Import <code>sqlite3</code> and <code>pandas</code></li>
<li>Read the panel with <code>pd.read_parquet</code> into <code>df</code></li>
<li>Open a connection to <code>":memory:"</code></li>
<li>Write <code>df</code> into a table called <code>wdi</code> with <code>to_sql</code>, using <code>index=False</code> and <code>if_exists="replace"</code></li>
<li>Copy your exercise 2 query across, unchanged</li>
<li>Replace <code>2015</code> with a <code>?</code> placeholder</li>
<li>Send the query with <code>pd.read_sql</code> and pass <code>params=(2015,)</code></li>
<li>Check that the five countries match exercise 2</li>
</ol>
</div><div class="column" style="width:48%;">
<p>What to look for:</p>
<ul>
<li>The SQL does not change, so everything you revised today is portable</li>
<li><code>params</code> takes a <span class="alert">tuple</span>, so the trailing comma in <code>(2015,)</code> matters</li>
<li>The result is a pandas DataFrame, printed with an index column</li>
<li>Change the parameter to 1995 and rerun, and only the results change</li>
<li>Assignment 09 asked for this pattern, and so may the quiz</li>
</ul>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;">
<p>Solution and the full output: <a href="#/sec-appendix-04"><span class="button">Appendix 04</span></a></p>
</div>
</div></div>
</div>
</section>
<section id="what-those-four-exercises-tested" class="slide level2">
<h2>What those four exercises tested</h2>
<h3 id="what-each-exercise-tested">What each exercise tested</h3>
<div style="margin-top: 20px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Exercise 1: <code>WHERE</code> with two conditions, an alias, <code>ORDER BY DESC</code>, and <code>LIMIT</code></li>
<li>Exercise 2: <code>GROUP BY</code> with <code>HAVING</code>, and the difference between <code>COUNT(*)</code> and <code>COUNT(value)</code></li>
<li>Exercise 3: a <code>LEFT JOIN</code> that keeps the left table whole, and a count that must skip the NULLs the join created</li>
<li>Exercise 4: the same SQL under <code>sqlite3</code>, with a <code>?</code> placeholder instead of a literal</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>If exercise 3 was hard, check the direction of the join
<ul>
<li>Write down which table must survive before you type <code>FROM</code></li>
</ul></li>
<li>If exercise 2 was hard, reread the evaluation ladder</li>
<li>The full solutions are in Appendices 01 to 04, with the outputs from this laptop</li>
<li>Lecture 22 has about thirty more queries, and Tutorial 04 on the website has the rest</li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="containers-and-docker" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Containers and Docker 🐳</h1>

</section>
<section id="why-working-code-breaks" class="slide level2">
<h2>Why working code breaks</h2>
<h3 id="why-working-code-breaks-1">Why working code breaks</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>“It works on my machine” happens when your code assumes software you never wrote down</li>
<li><span class="alert">Dependencies</span>: the external libraries and tools your code needs</li>
<li><span class="alert">Dependency management</span>: making sure it still runs next year</li>
<li>Libraries change: <code>print "hello"</code> was valid Python 2 and is a <code>SyntaxError</code> in Python 3</li>
<li>A 2016 Nature survey of 1,576 researchers found more than 70% had failed to reproduce someone else’s experiment, and more than half had failed to reproduce one of their own</li>
<li>Missing documentation and unrecorded dependencies have a technical fix</li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li>The ladder, from cheap to thorough:
<ul>
<li><span class="alert">Declare</span> your dependencies in one file in the repository root</li>
<li><span class="alert">Manage</span> them with an environment tool</li>
<li><span class="alert">Pin</span> them to exact versions</li>
<li><span class="alert">Containerise</span> the whole environment</li>
</ul></li>
<li>Your project sits at the last rung, because the marker’s machine has Docker and nothing else</li>
<li>Lecture 10’s ingredients of a reproducible result: code, data, environment, documentation
<ul>
<li>A container ships the environment with the code already inside it</li>
</ul></li>
</ul>
</div></div>
</div>
</section>
<section id="ways-to-pin-an-environment" class="slide level2">
<h2>Ways to pin an environment</h2>
<h3 id="venv-conda-and-uv-side-by-side">venv, conda and uv side by side</h3>
<div style="margin-top: 12px; font-size: 18px;">
<div class="columns">
<div class="column" style="width:33%;">
<p><span class="alert"><code>venv</code> and <code>pip</code></span></p>
<ul>
<li>Ships with Python</li>
<li><code>python3 -m venv .venv</code>, then <code>source .venv/bin/activate</code></li>
<li><code>pip freeze &gt; requirements.txt</code> writes <code>==</code> pins</li>
<li><code>pip install -r requirements.txt</code> reads them back</li>
<li>Two packages became seven lines, because pip lists the dependencies of your dependencies</li>
<li>Freeze inside conda and you get <code>name @ file:///...</code> paths that install nowhere else</li>
</ul>
</div><div class="column" style="width:33%;">
<p><span class="alert">conda</span></p>
<ul>
<li>Handles environments and packages together</li>
<li>Installs non-Python software: compilers, R, CUDA</li>
<li><code>conda create --name demo python=3.14 numpy</code></li>
<li><code>environment.yml</code> is the file you commit</li>
<li><code>--from-history</code> gives a file that travels between operating systems</li>
<li>You met it in DATASCI 151</li>
</ul>
</div><div class="column" style="width:33%;">
<p><span class="alert"><code>uv</code></span></p>
<ul>
<li>Written in Rust by Astral, and fast: eight packages resolved in 1.62 seconds</li>
<li><code>uv init</code>, <code>uv add polars</code>, <code>uv sync</code></li>
<li><code>pyproject.toml</code> for humans, <code>uv.lock</code> for the exact versions and hashes</li>
<li>Both files belong in git, and you never edit the lock by hand</li>
<li><code>uv export --format requirements-txt --no-hashes</code> writes the file your Dockerfile wants</li>
</ul>
</div></div>
<div style="background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;">
<p>Whichever tool you use, the deliverable is the same: <span class="alert"><code>requirements.txt</code></span> with <code>==</code> pins, in the repository root, because every Dockerfile reads it</p>
</div>
</div>
</section>
<section id="image-container-registry" class="slide level2">
<h2>Image, container, registry</h2>
<h3 id="what-each-word-means">What each word means</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>An <span class="alert">image</span> is a read-only template: operating system, libraries, your code, configuration
<ul>
<li>You build one from a <code>Dockerfile</code></li>
</ul></li>
<li>A <span class="alert">container</span> is a running instance of an image, and one image can start many</li>
<li>A <span class="alert">registry</span> is where images live, such as <a href="https://hub.docker.com">Docker Hub</a>
<ul>
<li><code>docker push</code> and <code>docker pull</code> move them</li>
</ul></li>
<li>A virtual environment isolates Python packages
<ul>
<li>A container also carries the system libraries, the interpreter and the tools your code touches</li>
</ul></li>
<li>A virtual machine boots a whole operating system
<ul>
<li>A container carries only what the application needs, so it starts in a second</li>
</ul></li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li>Docker Desktop is free for personal use, for open source, and for companies with fewer than 250 employees and under $10M in annual revenue</li>
<li>The personal plan caps Docker Hub at 100 image pulls per hour</li>
<li><span class="alert">Podman, Colima, OrbStack and Rancher Desktop</span> take the same commands, and every <code>docker</code> line in lecture 25 ran through OrbStack</li>
</ul>
<div style="text-align: center; margin-top: 10px;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/docker-architecture.png"><img data-src="figures/docker-architecture.png" style="width:66.0%"></a></p>
<div style="font-size: 17px;">
<p>Client, daemon and registry, from the <a href="https://docs.docker.com/get-started/docker-overview/">Docker documentation</a></p>
</div>
</div>
</div></div>
</div>
</section>
<section id="the-project-dockerfile" class="slide level2">
<h2>The project Dockerfile</h2>
<h3 id="what-each-block-does">What each block does</h3>
<div style="margin-top: 10px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:58%;">
<div style="font-size: 20px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode numberSource dockerfile number-lines code-with-copy"><code class="sourceCode dockerfile"><span id="cb11-1"><a></a><span class="co"># 1. Base image</span></span>
<span id="cb11-2"><a></a><span class="kw">FROM</span> ubuntu:24.04</span>
<span id="cb11-3"><a></a></span>
<span id="cb11-4"><a></a><span class="co"># 2. Build-time settings</span></span>
<span id="cb11-5"><a></a><span class="kw">ENV</span> DEBIAN_FRONTEND=noninteractive</span>
<span id="cb11-6"><a></a><span class="kw">SHELL</span> [<span class="st">"/bin/bash"</span>, <span class="st">"-c"</span>]</span>
<span id="cb11-7"><a></a></span>
<span id="cb11-8"><a></a><span class="co"># 3. System packages</span></span>
<span id="cb11-9"><a></a><span class="kw">RUN</span> <span class="ex">apt-get</span> update <span class="kw">&amp;&amp;</span> <span class="ex">apt-get</span> install <span class="at">-y</span> <span class="pp">[</span><span class="ss">...</span><span class="pp">]</span></span>
<span id="cb11-10"><a></a></span>
<span id="cb11-11"><a></a><span class="co"># 4. Quarto</span></span>
<span id="cb11-12"><a></a><span class="kw">ARG</span> QUARTO_VERSION=1.9.37</span>
<span id="cb11-13"><a></a><span class="kw">RUN</span> <span class="va">ARCH</span><span class="op">=</span><span class="va">$(</span><span class="ex">dpkg</span> <span class="at">--print-architecture</span><span class="va">)</span> <span class="kw">&amp;&amp;</span> <span class="ex">[...]</span></span>
<span id="cb11-14"><a></a></span>
<span id="cb11-15"><a></a><span class="co"># 5. Python environment</span></span>
<span id="cb11-16"><a></a><span class="kw">RUN</span> <span class="ex">python3</span> <span class="at">-m</span> venv /opt/venv</span>
<span id="cb11-17"><a></a><span class="kw">ENV</span> PATH=<span class="st">"/opt/venv/bin:$PATH"</span></span>
<span id="cb11-18"><a></a><span class="kw">COPY</span> requirements.txt /project/requirements.txt</span>
<span id="cb11-19"><a></a><span class="kw">RUN</span> <span class="ex">pip</span> install <span class="at">--no-cache-dir</span> <span class="at">-r</span> /project/requirements.txt</span>
<span id="cb11-20"><a></a></span>
<span id="cb11-21"><a></a><span class="co"># 6. Project files</span></span>
<span id="cb11-22"><a></a><span class="kw">WORKDIR</span> /project</span>
<span id="cb11-23"><a></a><span class="kw">COPY</span> . /project</span>
<span id="cb11-24"><a></a></span>
<span id="cb11-25"><a></a><span class="co"># 7. Default command</span></span>
<span id="cb11-26"><a></a><span class="kw">ENV</span> QUARTO_PYTHON=/opt/venv/bin/python</span>
<span id="cb11-27"><a></a><span class="kw">CMD</span> [<span class="st">"bash"</span>, <span class="st">"-c"</span>, <span class="st">"quarto render report.qmd &amp;&amp; [...]"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:42%;">
<ul>
<li><span class="alert"><code>FROM</code></span> pins the starting point to a tag
<ul>
<li><code>latest</code> moves, and a base image that moves breaks reproducibility</li>
</ul></li>
<li><code>ENV DEBIAN_FRONTEND=noninteractive</code> stops apt asking questions nobody is there to answer</li>
<li>Quarto arrives as a <code>.deb</code>, and <code>dpkg --print-architecture</code> picks arm64 or amd64</li>
<li>Ubuntu protects its own Python, so we build a virtual environment at <code>/opt/venv</code> and put it first on the <code>PATH</code></li>
<li><span class="alert"><code>COPY requirements.txt</code></span> sits alone above <code>COPY . /project</code>, so editing your report leaves the slow <code>pip install</code> cached</li>
<li>Fourteen instructions, of which eight create a layer, so the log counts <code>[1/8]</code> to <code>[8/8]</code></li>
</ul>
</div></div>
</div>
</section>
<section id="build-run-and-the-flags-that-matter" class="slide level2">
<h2>Build, run, and the flags that matter</h2>
<h3 id="layer-caching-volumes-and-ports">Layer caching, volumes, and ports</h3>
<div style="margin-top: 15px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:52%;">
<div style="font-size: 22px;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb12-1"><a></a>docker build -t datasci350-project .</span>
<span id="cb12-2"><a></a></span>
<span id="cb12-3"><a></a>docker run --rm \</span>
<span id="cb12-4"><a></a>  -v "$(pwd)/output:/project/output" \</span>
<span id="cb12-5"><a></a>  datasci350-project</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>The cold build took <span class="alert">7 minutes 00.70 seconds</span>: Quarto 206.5s, pip 89.2s, apt 70.8s</li>
<li>After a title edit, the rebuild took <span class="alert">0.837 seconds</span>, with seven of eight steps <code>CACHED</code></li>
<li>Edit <code>requirements.txt</code> instead and the cache misses at <code>COPY requirements.txt</code>, so pip and everything below it runs again</li>
<li><span class="alert"><code>.dockerignore</code></span> took the build context from 1.42MB to 59.36kB</li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li><code>--rm</code> deletes the container when it exits</li>
<li><span class="alert"><code>-v host:container</code></span> connects a folder on your laptop to one inside the container
<ul>
<li>The left path must be absolute, which is why we write <code>$(pwd)</code></li>
</ul></li>
<li>Without the mount the render succeeds, the container is deleted, and <code>report.html</code> goes with it
<ul>
<li>This is the most common Docker mistake in the course</li>
</ul></li>
<li><span class="alert"><code>-p host:container</code></span> does the same job for ports
<ul>
<li><code>docker run --rm -p 8888:8888 quay.io/jupyter/scipy-notebook</code> puts JupyterLab on <code>localhost:8888</code></li>
</ul></li>
<li>Our project writes a file, so it needs <code>-v</code> and no <code>-p</code></li>
</ul>
</div></div>
</div>
</section>
<section id="the-project-checklist" class="slide level2">
<h2>The project checklist</h2>
<h3 id="what-the-markers-machine-needs-to-render-your-report">What the marker’s machine needs to render your report</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:54%;">
<ul>
<li><span class="alert">Commit <code>data/raw/</code></span>. <code>report.qmd</code> reads the snapshot, and the API is never called at render time</li>
<li>Check it with <code>git ls-files data/raw</code>, which must print your files</li>
<li><span class="alert">Pin every package</span> in <code>requirements.txt</code> with <code>==</code>, and use a version that exists on PyPI</li>
<li><span class="alert">Test from a fresh clone</span> in an empty folder
<ul>
<li>The folder you wrote the code in already has the files you forgot to commit</li>
</ul></li>
<li>Run <code>ls output</code> after the container exits, and check the timestamp on the file</li>
<li>The five commands are 30% of the project grade, and you can run them tonight</li>
</ul>
</div><div class="column" style="width:46%;">
<div style="text-align: center;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/starter-report-rendered-2026.png"><img data-src="figures/starter-report-rendered-2026.png" style="width:86.0%"></a></p>
<div style="font-size: 17px;">
<p><code>output/report.html</code>, rendered inside the container</p>
</div>
</div>
<ul>
<li>My machine has Docker installed and nothing else: no Python, no Quarto, no packages</li>
<li>The exact commands I run are in <a href="#/sec-appendix-05"><span class="button">Appendix 05</span></a></li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="quiz-05-and-the-project" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Quiz 05 and the project 📝</h1>

</section>
<section id="what-to-expect-on-thursday" class="slide level2">
<h2>What to expect on Thursday</h2>
<h3 id="the-kind-of-question-each-lecture-brings">The kind of question each lecture brings</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert">Lecture 21</span>
<ul>
<li>Name the tool for a task and say why</li>
<li>Decide whether a small function is embarrassingly parallel</li>
<li>Do an Amdahl calculation with the numbers given</li>
</ul></li>
<li><span class="alert">Lecture 22</span>
<ul>
<li>Read a query and say what comes back</li>
<li>Fix a query that puts an aggregate in <code>WHERE</code></li>
<li>Say how many rows a given join returns, and what <code>COUNT</code> does with a NULL</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><span class="alert">Lecture 23</span>
<ul>
<li>Match <code>venv</code>, conda and <code>uv</code> to their files</li>
<li>Explain what <code>pip freeze</code> writes and what <code>==</code> means</li>
<li>Define image, container and registry</li>
</ul></li>
<li><span class="alert">Lecture 25</span>
<ul>
<li>Read a <code>Dockerfile</code> block and say what it does</li>
<li>Explain why <code>COPY requirements.txt</code> comes before <code>COPY .</code></li>
<li>Say what happens to the report without <code>-v</code></li>
</ul></li>
<li>The quiz is in class on Thursday 3 December, open book and open notes, and it is worth 6%</li>
</ul>
</div></div>
</div>
</section>
<section id="how-to-revise" class="slide level2 scrollable">
<h2>How to revise</h2>
<h3 id="a-two-hour-plan-in-order">A two-hour plan, in order</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<ol type="1">
<li>Reread the summary slide of each lecture, where every alert term is fair game</li>
<li>Redo today’s four SQL exercises without looking at the appendices</li>
<li>Redo the lecture 25 exercise: add a package, rebuild, and read which steps say <code>CACHED</code></li>
<li>Do the Amdahl arithmetic for 95% parallel on 4 cores and on 64, then compare</li>
<li>Open lecture 22 and read three queries out loud, clause by clause, in evaluation order</li>
</ol>
</div><div class="column" style="width:48%;">
<ul>
<li>The appendices you want:
<ul>
<li>Lecture 21, Appendix 02: chunk sizes compared</li>
<li>Lecture 22, Appendix 04: the complete <code>sqlite3</code> listing</li>
<li>Lecture 23, Appendix 02: six build errors and their fixes</li>
<li>Lecture 25, Appendix 03: the complete Dockerfile, with comments</li>
</ul></li>
<li>Tutorial 04 on the course website is the longer SQL revision if any clause still feels new</li>
<li>Email me before Thursday if a topic is still unclear, and we can meet in office hours</li>
</ul>
</div></div>
</div>
</section>
<section id="project-questions" class="slide level2">
<h2>Project questions</h2>
<h3 id="the-problems-i-expect-to-hear-about">The problems I expect to hear about</h3>
<div style="margin-top: 15px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li><span class="alert">The data is not in the repository</span>
<ul>
<li>The build succeeds, because nothing in the Dockerfile mentions your CSV, and the run dies with <code>FileNotFoundError</code></li>
<li>Fix it with <code>git add data/raw/</code>, then check with <code>git ls-files data/raw</code></li>
</ul></li>
<li><span class="alert">A pin that does not exist</span>
<ul>
<li>pip stops the build, and nothing below that layer is cached</li>
<li>Read the version numbers in your <code>requirements.txt</code> against PyPI</li>
</ul></li>
<li><span class="alert">The mount is missing</span>
<ul>
<li>The report renders, the container is deleted, and <code>ls output</code> says no such directory</li>
<li>Add <code>-v "$(pwd)/output:/project/output"</code></li>
</ul></li>
</ul>
</div><div class="column" style="width:48%;">
<ul>
<li>Where the answers live:
<ul>
<li>Failures one and two: <a href="https://danilofreire.github.io/datasci350/lectures/lecture-25/25-docker.html">Lecture 25</a>, the “When something goes wrong” section</li>
<li>Seven build and run errors: Lecture 25, Appendix 02</li>
<li>Six installation errors: <a href="https://danilofreire.github.io/datasci350/lectures/lecture-23/23-containers.html">Lecture 23</a>, Appendix 02</li>
</ul></li>
<li>Bring me your build log rather than a description of it
<ul>
<li>The log names the step that failed</li>
</ul></li>
<li>What else is blocking your group today?</li>
</ul>
</div></div>
</div>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Summary</h1>

</section>
<section id="what-to-revise-before-thursday" class="slide level2">
<h2>What to revise before Thursday</h2>
<h3 id="the-vocabulary-in-the-order-we-met-it-today">The vocabulary, in the order we met it today</h3>
<div style="margin-top: 20px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="alert">Serial and parallel</span> work, <code>map</code>, and problems that are <span class="alert">embarrassingly parallel</span></li>
<li><span class="alert"><code>joblib</code></span> for numeric loops, <code>ProcessPoolExecutor</code> for CPU work, <code>ThreadPoolExecutor</code> for waiting</li>
<li><span class="alert">Big O</span>: parallelism divides the constant and leaves the class alone</li>
<li><span class="alert">Amdahl’s law</span>: 90% parallel on 8 cores gives 4.7×</li>
<li><span class="alert">The GIL</span>: threads help while Python waits, processes help while Python computes</li>
<li><span class="alert">Dask</span> is lazy until <code>.compute()</code>, and on 200 million rows DuckDB finished in 0.53 s against pandas at 9.65 s</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>The <span class="alert">evaluation ladder</span>: <code>FROM</code>, <code>WHERE</code>, <code>GROUP BY</code>, <code>HAVING</code>, then <code>SELECT</code></li>
<li><span class="alert"><code>WHERE</code></span> filters rows and <span class="alert"><code>HAVING</code></span> filters groups</li>
<li><code>COUNT(*)</code> counts rows and <code>COUNT(value)</code> counts numbers</li>
<li>The three joins gave 5, 6 and 7 rows on the same two tables</li>
<li><span class="alert"><code>sqlite3</code></span> wants a connection, a cursor, <code>commit()</code>, and <code>?</code> placeholders</li>
<li><span class="alert"><code>requirements.txt</code></span> with <code>==</code> pins, whichever tool wrote it</li>
<li><span class="alert">Image, container, registry</span>, and the <code>-v</code> flag that puts the report on your laptop</li>
</ul>
</div></div>
</div>
</section>
<section id="before-we-finish" class="slide level2">
<h2>Before we finish</h2>
<div style="margin-top: 25px; font-size: 22px;">
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li>Thank you for a good semester
<ul>
<li>You have gone from <code>cd</code> and <code>ls</code> to shipping an image someone else can run</li>
</ul></li>
<li><span class="alert">Quiz 05</span> is on Thursday 3 December and covers Lectures 21, 22, 23 and 25</li>
<li>The <span class="alert">final project</span> is due on Tuesday 8 December at 11:59pm</li>
<li>We meet on 8 December for a Q&amp;A session and project work time, with no lecture</li>
<li>Test your container from a fresh clone tonight, while there is still time to fix it</li>
<li>Please fill in the <span class="alert">course evaluation</span>
<ul>
<li>I read every comment, and this course changes every year because of them</li>
</ul></li>
</ul>
</div><div class="column" style="width:45%;">
<div style="text-align: center;">
<p><a href="#/" data-modal-type="image" data-modal-url="figures/starter-repo-github-2026.png"><img data-src="figures/starter-repo-github-2026.png" style="width:100.0%"></a></p>
<div style="font-size: 17px;">
<p>Source: <a href="https://github.com/danilofreire/datasci350-project-starter">datasci350-project-starter</a></p>
</div>
</div>
</div></div>
</div>
</section></section>
<section id="questions" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Questions? 🤔</h1>

</section>

<section id="thank-you-very-much" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Thank you very much! 🙏</h1>

</section>

<section>
<section id="appendix" class="title-slide slide level1 center" data-background-color="#1B3A6B">
<h1>Appendix 📚</h1>

</section>
<section id="sec-appendix-01" class="slide level2">
<h2>Appendix 01: Solution to Exercise 01</h2>
<div style="margin-top: 20px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:52%;">
<div style="font-size: 20px;">
<div id="fd171b9e" class="cell" data-cache="true" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb13-2"><a></a><span class="st">    SELECT country,</span></span>
<span id="cb13-3"><a></a><span class="st">           ROUND(value, 1) AS co2_pc</span></span>
<span id="cb13-4"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb13-5"><a></a><span class="st">    WHERE indicator = 'co2_per_capita'</span></span>
<span id="cb13-6"><a></a><span class="st">      AND year = 2020</span></span>
<span id="cb13-7"><a></a><span class="st">    ORDER BY value DESC</span></span>
<span id="cb13-8"><a></a><span class="st">    LIMIT 5</span></span>
<span id="cb13-9"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>┌─────────────────────┬────────┐
│       country       │ co2_pc │
│       varchar       │ double │
├─────────────────────┼────────┤
│ Palau               │   71.7 │
│ Qatar               │   41.3 │
│ Bahrain             │   25.0 │
│ Brunei Darussalam   │   22.6 │
│ Trinidad and Tobago │   21.8 │
└─────────────────────┴────────┘</code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:48%;">
<ul>
<li><code>WHERE</code> drops every other indicator and every other year</li>
<li><code>ROUND(value, 1)</code> computes a new column, and <code>AS co2_pc</code> names it</li>
<li><code>ORDER BY value DESC</code> sorts on the original column, which works just as well as sorting on the alias</li>
<li>Palau reports 71.7 tonnes per person, four times the second place, with fewer than 20,000 residents and a large tourist economy</li>
<li>Qatar, Bahrain, Brunei and Trinidad and Tobago follow, all of them oil or gas producers</li>
</ul>
<p><a href="#/sec-exercise-01"><span class="button">Back to the exercise</span></a></p>
</div></div>
</div>
</section>
<section id="sec-appendix-02" class="slide level2">
<h2>Appendix 02: Solution to Exercise 02</h2>
<div style="margin-top: 20px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:52%;">
<div style="font-size: 20px;">
<div id="abf6bbe9" class="cell" data-cache="true" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb15-2"><a></a><span class="st">    SELECT country,</span></span>
<span id="cb15-3"><a></a><span class="st">           COUNT(value) AS n_years,</span></span>
<span id="cb15-4"><a></a><span class="st">           ROUND(AVG(value), 1) AS mean_internet</span></span>
<span id="cb15-5"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb15-6"><a></a><span class="st">    WHERE indicator = 'internet_users_pct'</span></span>
<span id="cb15-7"><a></a><span class="st">      AND year &gt;= 2015</span></span>
<span id="cb15-8"><a></a><span class="st">    GROUP BY country</span></span>
<span id="cb15-9"><a></a><span class="st">    HAVING COUNT(value) &gt;= 5</span></span>
<span id="cb15-10"><a></a><span class="st">       AND AVG(value) &gt; 95</span></span>
<span id="cb15-11"><a></a><span class="st">    ORDER BY mean_internet DESC</span></span>
<span id="cb15-12"><a></a><span class="st">    LIMIT 5</span></span>
<span id="cb15-13"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>┌────────────┬─────────┬───────────────┐
│  country   │ n_years │ mean_internet │
│  varchar   │  int64  │    double     │
├────────────┼─────────┼───────────────┤
│ Iceland    │       9 │          98.7 │
│ Bahrain    │       9 │          98.4 │
│ Luxembourg │       9 │          97.9 │
│ Qatar      │       9 │          97.8 │
│ Denmark    │       9 │          97.5 │
└────────────┴─────────┴───────────────┘</code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:48%;">
<ul>
<li><code>WHERE</code> keeps rows, and both <code>HAVING</code> conditions test the group</li>
<li><code>COUNT(value)</code> returns 9 for each of these countries, so the panel holds 2015 to 2023</li>
<li><code>COUNT(*)</code> would return 9 for every country in the world, including the ones with no numbers at all</li>
<li>Iceland leads at 98.7%, with Bahrain, Luxembourg, Qatar and Denmark behind it</li>
<li><code>ORDER BY</code> names <code>mean_internet</code>, the alias created in <code>SELECT</code></li>
</ul>
<p><a href="#/sec-exercise-02"><span class="button">Back to the exercise</span></a></p>
</div></div>
</div>
</section>
<section id="sec-appendix-03" class="slide level2">
<h2>Appendix 03: Solution to Exercise 03</h2>
<div style="margin-top: 12px; font-size: 19px;">
<div class="columns">
<div class="column" style="width:50%;">
<div style="font-size: 20px;">
<div id="072e8e03" class="cell" data-cache="true" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb17-2"><a></a><span class="st">    SELECT r.region,</span></span>
<span id="cb17-3"><a></a><span class="st">           COUNT(g.country) AS countries_with_gdp,</span></span>
<span id="cb17-4"><a></a><span class="st">           ROUND(AVG(g.gdp_per_capita), 0) AS mean_gdp</span></span>
<span id="cb17-5"><a></a><span class="st">    FROM regions AS r</span></span>
<span id="cb17-6"><a></a><span class="st">    LEFT JOIN gdp2022 AS g ON g.iso3 = r.iso3</span></span>
<span id="cb17-7"><a></a><span class="st">    GROUP BY r.region</span></span>
<span id="cb17-8"><a></a><span class="st">    ORDER BY mean_gdp DESC NULLS LAST</span></span>
<span id="cb17-9"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>┌────────────────────┬────────────────────┬──────────┐
│       region       │ countries_with_gdp │ mean_gdp │
│      varchar       │       int64        │  double  │
├────────────────────┼────────────────────┼──────────┤
│ North America      │                  1 │  64322.0 │
│ Europe             │                  1 │  38868.0 │
│ East Asia          │                  1 │  11830.0 │
│ Latin America      │                  1 │   9032.0 │
│ South Asia         │                  1 │   2098.0 │
│ Sub-Saharan Africa │                  0 │     NULL │
└────────────────────┴────────────────────┴──────────┘</code></pre>
</div>
</div>
</div>
<ul>
<li><code>regions</code> goes on the left, because every region must survive</li>
<li>Sub-Saharan Africa comes back with 0 countries and a NULL mean</li>
</ul>
</div><div class="column" style="width:50%;">
<p>The two counts side by side:</p>
<div style="font-size: 20px;">
<div id="a3af29a5" class="cell" data-cache="true" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a></a>duckdb.sql(<span class="st">"""</span></span>
<span id="cb19-2"><a></a><span class="st">    SELECT r.region,</span></span>
<span id="cb19-3"><a></a><span class="st">           COUNT(*) AS count_star,</span></span>
<span id="cb19-4"><a></a><span class="st">           COUNT(g.country) AS count_country</span></span>
<span id="cb19-5"><a></a><span class="st">    FROM regions AS r</span></span>
<span id="cb19-6"><a></a><span class="st">    LEFT JOIN gdp2022 AS g ON g.iso3 = r.iso3</span></span>
<span id="cb19-7"><a></a><span class="st">    GROUP BY r.region</span></span>
<span id="cb19-8"><a></a><span class="st">    ORDER BY r.region</span></span>
<span id="cb19-9"><a></a><span class="st">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>┌────────────────────┬────────────┬───────────────┐
│       region       │ count_star │ count_country │
│      varchar       │   int64    │     int64     │
├────────────────────┼────────────┼───────────────┤
│ East Asia          │          2 │             1 │
│ Europe             │          1 │             1 │
│ Latin America      │          1 │             1 │
│ North America      │          1 │             1 │
│ South Asia         │          1 │             1 │
│ Sub-Saharan Africa │          1 │             0 │
└────────────────────┴────────────┴───────────────┘</code></pre>
</div>
</div>
</div>
<ul>
<li><code>COUNT(*)</code> counts the empty row a left join creates, so East Asia looks like 2 and Sub-Saharan Africa like 1</li>
</ul>
<p><a href="#/sec-exercise-03"><span class="button">Back to the exercise</span></a></p>
</div></div>
</div>
</section>
<section id="sec-appendix-04" class="slide level2">
<h2>Appendix 04: Solution to Exercise 04</h2>
<div style="margin-top: -8px; font-size: 20px;">
<div class="columns">
<div class="column" style="width:44%;">
<div style="font-size: 20px;">
<div id="a18af546" class="cell" data-cache="true" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a></a><span class="im">import</span> sqlite3</span>
<span id="cb21-2"><a></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb21-3"><a></a></span>
<span id="cb21-4"><a></a>df <span class="op">=</span> pd.read_parquet(</span>
<span id="cb21-5"><a></a>    <span class="st">"../lecture-19/data/wdi_panel.parquet"</span>)</span>
<span id="cb21-6"><a></a></span>
<span id="cb21-7"><a></a>conn <span class="op">=</span> sqlite3.<span class="ex">connect</span>(<span class="st">":memory:"</span>)</span>
<span id="cb21-8"><a></a>df.to_sql(<span class="st">"wdi"</span>, conn, index<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb21-9"><a></a>          if_exists<span class="op">=</span><span class="st">"replace"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div><div class="column" style="width:56%;">
<div style="font-size: 20px;">
<div id="eabbd3a7" class="cell" data-cache="true" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a></a>pd.read_sql(<span class="st">"""</span></span>
<span id="cb22-2"><a></a><span class="st">    SELECT country,</span></span>
<span id="cb22-3"><a></a><span class="st">           COUNT(value) AS n_years,</span></span>
<span id="cb22-4"><a></a><span class="st">           ROUND(AVG(value), 1) AS mean_internet</span></span>
<span id="cb22-5"><a></a><span class="st">    FROM wdi</span></span>
<span id="cb22-6"><a></a><span class="st">    WHERE indicator = 'internet_users_pct'</span></span>
<span id="cb22-7"><a></a><span class="st">      AND year &gt;= ?</span></span>
<span id="cb22-8"><a></a><span class="st">    GROUP BY country</span></span>
<span id="cb22-9"><a></a><span class="st">    HAVING COUNT(value) &gt;= 5</span></span>
<span id="cb22-10"><a></a><span class="st">       AND AVG(value) &gt; 95</span></span>
<span id="cb22-11"><a></a><span class="st">    ORDER BY mean_internet DESC</span></span>
<span id="cb22-12"><a></a><span class="st">    LIMIT 5</span></span>
<span id="cb22-13"><a></a><span class="st">"""</span>, conn, params<span class="op">=</span>(<span class="dv">2015</span>,))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th">n_years</th>
<th data-quarto-table-cell-role="th">mean_internet</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Iceland</td>
<td>9</td>
<td>98.7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Bahrain</td>
<td>9</td>
<td>98.4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Luxembourg</td>
<td>9</td>
<td>97.9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Qatar</td>
<td>9</td>
<td>97.8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Denmark</td>
<td>9</td>
<td>97.5</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</div></div>
<div style="font-size: 17px; margin-top: -11px;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>The SQL is identical to Appendix 02, apart from the <code>?</code></li>
<li><code>params=(2015,)</code> passes a tuple with one element
<ul>
<li>Drop the comma and Python hands SQLite an integer, which it refuses</li>
</ul></li>
<li><code>pd.read_sql</code> returns a DataFrame, so the output carries an index column DuckDB’s printed table does not</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>The same five countries and the same means come back</li>
<li>Swap <code>":memory:"</code> for <code>"wdi.db"</code> and the table survives the script</li>
</ul>
<p><a href="#/sec-exercise-04"><span class="button">Back to the exercise</span></a></p>
</div></div>
</div>
</div>
</section>
<section id="sec-appendix-05" class="slide level2">
<h2>Appendix 05: Checking your container</h2>
<h3 id="the-commands-i-run-on-your-repository">The commands I run on your repository</h3>
<div style="margin-top: 20px; font-size: 21px;">
<div class="columns">
<div class="column" style="width:54%;">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb23-1"><a></a>git clone &lt;your repo url&gt; fresh-test</span>
<span id="cb23-2"><a></a>cd fresh-test</span>
<span id="cb23-3"><a></a>docker build -t datasci350-project .</span>
<span id="cb23-4"><a></a>docker run --rm \</span>
<span id="cb23-5"><a></a>  -v "$(pwd)/output:/project/output" \</span>
<span id="cb23-6"><a></a>  datasci350-project</span>
<span id="cb23-7"><a></a>open output/report.html</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>The machine has Docker installed and nothing else: no Python, no Quarto, no packages</li>
<li>There is internet during the build, and none promised during the run</li>
</ul>
</div><div class="column" style="width:46%;">
<ul>
<li>Check that the snapshot is committed:</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb24-1"><a></a>git ls-files data/raw</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li>It should print your data files, and an empty answer means the render fails inside the container</li>
<li>Build errors: <a href="https://danilofreire.github.io/datasci350/lectures/lecture-23/23-containers.html#sec-appendix-02">Lecture 23, Appendix 02</a></li>
<li>Run errors: <a href="https://danilofreire.github.io/datasci350/lectures/lecture-25/25-docker.html#sec-appendix-02">Lecture 25, Appendix 02</a></li>
</ul>
</div></div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://danilofreire.github.io/datasci350/lectures/lecture-26/26-revision.html">Revision</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/multimodal/multimodal.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, Multimodal, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>